### ISSUE TITLE
[Help]: Cannot complete unwrapping - Terminated / semlock + semaphore errors

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#10]
System:
Python 3.10.6
Ubuntu 22.04
RAM 240 GB
Processor 16 vCores

My code:

> import platform, sys, os
> 
> from pygmtsar import SBAS
> 
> import xarray as xr
> import numpy as np
> import pandas as pd
> # supress numpy warnings
> import warnings
> warnings.filterwarnings('ignore')
> 
> sbas = SBAS('raw_orig', dem_filename='topo/DEM_WGS84.nc', basedir='raw_stack', landmask_filename='landmask/landmask.nc').set_master('2021-06-04')
> sbas.download_orbits()
> 
> # About 16GB RAM for this stack, 4 minutes (12)
> sbas.stack_parallel()
> 
> baseline_pairs = sbas.baseline_pairs(days=50, meters=100)
> 
> # Under 1 min
> sbas.topo_ra_parallel()
> topo_ra = sbas.get_topo_ra()
> 
> 
> pairs = baseline_pairs[['ref_date', 'rep_date']]
> 
> # About 27 min (34)
> sbas.intf_parallel(pairs, wavelength=100)
> 
> 
> # Fix merging bug
> sbas.to_dataframe().sort_values(by=["date","subswath"],inplace=True)
> # About 14GB RAM, 3.5 min (34 ss) (72 topo)
> sbas.merge_parallel(pairs)
> 
> phasefilts = sbas.open_grids(pairs, 'phasefilt')
> phasefilts_ll = sbas.open_grids(pairs, 'phasefilt', geocode=True)
> corrs = sbas.open_grids(pairs, 'corr')
> 
> landmask_ll = sbas.get_landmask()
> landmask_ra = sbas.get_landmask(inverse_geocode=True)
> filter = lambda corr, unwrap: xr.where(corr_stack>=0.1, unwrap, np.nan)
> snaphuconf = sbas.snaphu_config(defomax=0, NTILEROW=4, NTILECOL=4, ROWOVRLP=400, COLOVRLP=400)
> 
> # About 38GB RAM (4x4 tiles, 16 procs, 1 job)
> sbas.unwrap_parallel(pairs, n_jobs=1, func=filter, conf=snaphuconf, mask=landmask_ra)

![image](https://user-images.githubusercontent.com/50405969/197048874-5efd4f1f-8092-4618-9d0e-ddf94f1a3ef9.png)

**Comment by SteffanDavies** [comment]
I am now trying unwrapping with only 1 subswath (F2) and get a different error:

FileNotFoundError: [Errno 2] No such file or directory: 'raw_stack/F2_20210511_20210523_unwrap.out'

![image](https://user-images.githubusercontent.com/50405969/197084660-a3817243-6860-409c-bb05-393198db7aca.png)

Workdir:

![image](https://user-images.githubusercontent.com/50405969/197084758-aa1553e4-3daf-48b2-9442-d35057c45558.png)

Snaphu tiledir:

![image](https://user-images.githubusercontent.com/50405969/197084796-d02bcbe7-0181-44f4-8ad1-c141ba6523a4.png)

**Comment by SteffanDavies** [comment]
I noticed sbas.snaphu_config lists TILEDIR as master filename. Is this a problem for SBAS stack of multiple pairs? Or does your code change the TILEDIR on the fly?

**Comment by mobigroup** [comment]
> I noticed sbas.snaphu_config lists TILEDIR as master filename. Is this a problem for SBAS stack of multiple pairs? Or does your code change the TILEDIR on the fly?

Yes, for parallel unwrapping the TILEDIR path is different for the every ref-rep pair, see the code below:

```
    def unwrap_parallel(self, pairs, n_jobs=-1, **kwargs):
...
        def unwrap(subswath, pair, **kwargs):
            # define unique tiledir name for parallel processing
            if 'conf' in kwargs:
                dirname = f'F{subswath}_{"_".join(pair).replace("-","")}_snaphu_tiledir'
                dirpath = os.path.join(self.basedir, dirname)
                kwargs['conf'] += f'    TILEDIR {dirpath}'
            return self.unwrap(subswath, pair, **kwargs)
...
```

TILEDIR as master filename is applied for 'unwrap' function designed to process a single grid to check the parameters. Please try to unwrap a single interferogram in 'debug' mode to see SNAPHU logs and errors (/dev/stdout and /dev/stderr):

```
unwrap, conn = sbas.unwrap(sbas.get_subswath(), pairs.values[0],
                           func=filter, conf=snaphuconf, mask=landmask_ra, conncomp=True, debug=True)
```

**Comment by SteffanDavies** [comment]
Yes, I read your code a few hours ago and TILEDIR is correctly created on the fly. 

I am currently unwrapping parallel in debug mode.

**Comment by mobigroup** [comment]
@SteffanDavies Does it work for you now?
