### ISSUE TITLE
[Bug]: Error generating interferograms in Yamchi Dam notebook example 

### ISSUE THREAD

**Issue by benwright-davra** [mobigroup/gmtsar#105]
**Describe the bug**
Generation starts as expected however seems to stop before the first queue has been generated completely. Only thing that I have changed is the asf log-in details.

**To Reproduce**
Pull new docker image (https://hub.docker.com/r/pechnikov/pygmtsar) and run YamchiDam.ipynb example. 

**System and software version:**
 - OS: Linux Mint
 - PyGMTSAR version: docker.io/pechnikov/pygmtsar (tag = latest)

**Processing Log**
[yamchi_dam_output.txt](https://github.com/AlexeyPechnikov/pygmtsar/files/14343447/yamchi_dam_output.txt)
[yamchi_dam_output2.txt](https://github.com/AlexeyPechnikov/pygmtsar/files/14343521/yamchi_dam_output2.txt)

**Comment by AlexeyPechnikov** [comment]
Try to remove this code completely (to use the default NetCDF5 library) and re-run the example: 
```
if os.path.exists('/.dockerenv') and not 'google.colab' in sys.modules:
    # use different NetCDF backend in Docker containers
    from pygmtsar import datagrid
    datagrid.netcdf_engine = 'netcdf4'
```

Please let me know about your results. Docker containers work tricky sometimes... For me and some other users, the default NetCDF5 library returns similar error and the NetCDF4 library works well.

**Comment by benwright-davra** [comment]
Your suggestion resolves this issue.

**Comment by AlexeyPechnikov** [comment]
@benwright-davra Great! Please specify your hardware for reference. It is x64 or arm64 architecture based or something different?

**Comment by benwright-davra** [comment]
Thanks and sure, please see below:
Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.6.8
Processor: 14-core (6-mt/8-st) model: 12th Gen Intel Core i7-12700H bits: 64 type: MST AMCP, Arch: Alder Lake
