### ISSUE TITLE
[Help]: Align images error

### ISSUE THREAD

**Issue by gokceyagmurbudak** [mobigroup/gmtsar#114]
**I am investigating the 2023 Türkiye Earthquake for the Hatay region.

my inputs:**

_SCENES = ['S1A_IW_SLC__1SDV_20230128T153358_20230128T153426_046986_05A2B6_1629',
          'S1A_IW_SLC__1SDV_20230209T153357_20230209T153425_047161_05A88A_BB1A']
POLARIZATION = 'VV'
ORBIT        = 'A'
SUBSWATH     = 123_

I didnt assign a resolution variable to work with default value. But I got an error from align images part;

if os.path.exists('/.dockerenv') and not 'google.colab' in sys.modules:
    # use special joblib backend in Docker containers
    sbas.compute_align(joblib_aligning_backend='threading')
else:
    sbas.compute_align()

_____________________________________________________________________
Aligning Reference: 100%
 3/3 [01:07<00:00, 19.92s/it]
Aligning Repeat: 100%
 3/3 [11:19<00:00, 207.37s/it]
**---------------------------------------------------------------------------
InvalidIndexError                         Traceback (most recent call last)
<ipython-input-57-332a25bc9dd4> in <cell line: 1>()
      3     sbas.compute_align(joblib_aligning_backend='threading')
      4 else:
----> 5     sbas.compute_align()

6 frames
/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   3883 
   3884         if not self._index_as_unique:
-> 3885             raise InvalidIndexError(self._requires_unique_msg)
   3886 
   3887         if len(target) == 0:

InvalidIndexError: Reindexing only valid with uniquely valued Index objects**

**Could this have something to do with changing the DEM type or not writing the resolution?

Also, why was the resolution of the Türkiye earthquake on the notebook given as 200?**

thank you in advance

**Comment by AlexeyPechnikov** [comment]
It seems the scenes are not overlapped or DEM is incomplete.

The resolution is selected to fit free Google Colab limitations to complete the processing (2 vCPU cores and about 12 GB RAM).
