### ISSUE TITLE
[Help]: why this is happened ?

### ISSUE THREAD

**Issue by mbahmu25** [mobigroup/gmtsar#117]
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/aaa523a1-bdf3-46c5-8d49-0d6539281aaa)

**Comment by AlexeyPechnikov** [comment]
It looks like an incorrect alignment result, possibly due to an incorrect DEM.

**Comment by mbahmu25** [comment]
The data is same as in colab, i didnt change anything

**Comment by AlexeyPechnikov** [comment]
But do you use a local or dockerized installation?

**Comment by mbahmu25** [comment]
Local

**Comment by AlexeyPechnikov** [comment]
Ok, please try the exact Python version:
```
python3.11 --version
Python 3.11.8
```

Also, you can install the exact Python libraries following [PyGMTSAR Dockerfile](https://github.com/AlexeyPechnikov/pygmtsar/blob/pygmtsar2/docker/pygmtsar.Dockerfile):

```
pip3.11 install \
    adjustText==1.0.4 \
    asf_search==7.0.4 \
    dask==2024.1.1 \
    distributed==2024.1.1 \
    geopandas==0.14.3 \
    h5netcdf==1.3.0 \
    h5py==3.10.0 \
    imageio==2.31.5 \
    ipywidgets==8.1.1 \
    joblib==1.3.2 \
    matplotlib==3.8.0 \
    nc-time-axis==1.4.1 \
    numba==0.57.1 \
    numpy==1.24.4 \
    pandas==2.2.1 \
    remotezip==0.12.2 \
    rioxarray==0.15.1 \
    scikit-learn==1.3.1 \
    scipy==1.11.4 \
    seaborn==0.13.0 \
    shapely==2.0.3 \
    statsmodels==0.14.0 \
    tqdm==4.66.1 \
    xarray==2024.2.0 \
    xmltodict==0.13.0 \
    pygmtsar
```

**Comment by mbahmu25** [comment]
the result is still same as before after i install that

**Comment by AlexeyPechnikov** [comment]
Have you installed all the exact library versions and restarted your notebooks server process?

**Comment by mbahmu25** [comment]
yes

**Comment by AlexeyPechnikov** [comment]
It might be difficult to debug: perhaps you are using Anaconda or another Python package manager that has incompatible modifications, or your GMTSAR binaries installation is incorrect. Using Docker Desktop with the PyGMTSAR Docker image for local processing would be a simpler alternative.

**Comment by mbahmu25** [comment]
ah i see, yes i'm using anaconda, i will try docker for safer option, Thankyou.
