### ISSUE TITLE
[Help]: sbas_parallel stalled?

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#12]
sbas_parallel claims 100% but hasn't concluded for over an hour, and only using 100% of 1 cpu.

![image](https://user-images.githubusercontent.com/50405969/198349539-87f53619-7d3d-4451-8291-1b6555d88434.png)
![image](https://user-images.githubusercontent.com/50405969/198349838-04ce68d8-678b-4243-9e1f-3764d79b42b3.png)
![image](https://user-images.githubusercontent.com/50405969/198350227-c6d3e6e7-6e69-4635-a562-2bfb1a3a4cb7.png)

Is this normal?

Last files created in processing dir where disp_chunk*.grd

**Comment by SteffanDavies** [comment]
It finally finished and is in the Saving phase. Took almost 2 hours.

![image](https://user-images.githubusercontent.com/50405969/198364412-eea05be3-5204-440f-84cf-e7a03a879d32.png)

**Comment by SteffanDavies** [comment]
I have changed to n_jobs=4 to limit swap usage and it's been stuck for 16 hours.

**Comment by mobigroup** [comment]
Hi @SteffanDavies Recently I’ve checked the sbas_parallel() function on 2 stitched scenes using 15m resolution without any issue so it should work well. Please show how do you define the corr_stack variable for your mask?

**Comment by mobigroup** [comment]
@SteffanDavies Maybe some updates about the processing? As I mentioned above I can imagine just one case to produce the issue when you use not materialized mask (without .compute() call) for the processing so you ask the sbas_parallel() function to read and aggregate the full correlation grids stack in 16 parallel processes (for 38 interferograms for 2 full scenes the stack size is about 100GB size and 16 stacks are 1.6 TB size). We need to use NumPy array inside Xarray dataarray for the mask but not the lazy Dask array which returns sbas.open_grids() function. All the details available in the example notebooks here: https://github.com/mobigroup/YamchiDam/tree/main/notebooks

**Comment by mobigroup** [comment]
@SteffanDavies Do you have some updates maybe?
