### ISSUE TITLE
wavelength using in InSAR sentinal1

### ISSUE THREAD

**Issue by mhotalebi** [mobigroup/gmtsar#121]
Dear Alexey Pechnikov
thanks for creating gmtsar.
I am recently run your Golden Valley, CA code. In this code you use wavelength 30 for sentinal1 which have c band frequency, but when i checked this  wavelength  is 56 mm. can you explain why you choose this wavelength.
Sincerely

**Comment by AlexeyPechnikov** [comment]
Thank you. However, please note that GMTSAR and SNAPHU are independent projects utilized as external binaries within PyGMTSAR.
The 'wavelength' parameter refers to the size of the Gaussian filter used for spatial filtering to reduce speckle noise and define correlation, not to the radar wavelength itself.

**Comment by mhotalebi** [comment]
Thank you for your response earlier!  I just wanted to ask if the wavelength you suggested (30 ) is a general recommendation suitable for all projects, or if it needs to be calculated individually for each project's specifications.

**Comment by mhotalebi** [comment]
I'm still learning about all this, especially about the wavelength for the Gaussian filter. Do you think it changes a lot between projects, or is there usually one number that works okay? Just trying to figure out what to do for different projects. if there is a easy to understand reference I would be happy to inform me.
thanks again

**Comment by AlexeyPechnikov** [comment]
To apply the PS approach effectively, we need to select a small wavelength, typically around 30 meters, to ensure that single-pixel scatterers are not missed while still allowing for correlation computation. For SBAS processing, we use a larger wavelength, typically around 200 meters, to better detect distributed scatterers.

**Comment by mhotalebi** [comment]
excuse me recently when I wanna run pygmtsar code cant import ESA and  this error shows to me:
cannot import name 'ESA' from 'pygmtsar' (/usr/local/lib/python3.10/dist-packages/pygmtsar/__init__.py)
what should I do?
Sincerely

**Comment by AlexeyPechnikov** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7186282489739460608/

**Comment by mhotalebi** [comment]
recently I run new version of your InSAR model (GoldenValley)and when model run below line Found inconsistent set of .tiff and .xml files in it.
 # scan the data directory for SLC scenes and download missed orbits
S1.download_orbits(DATADIR, S1.scan_slc(DATADIR))
