### ISSUE TITLE
[Help]: ASF SLC download throwing errors recently

### ISSUE THREAD

**Issue by benwright-davra** [mobigroup/gmtsar#123]
**Describe the problem you encountered**
Hi Alexey, recently (for the last couple of days) I've been having issues with ASF from your docker image that previously worked fine. I suspect it's a similar thing to the problem that's been happening with the orbits - whereby things simply aren't stable enough, but I thought I'd check to see whether it could be some new incompatibility. If it is similar to the orbits, do you think it would be possible to provide a backup to ASF for data as well as orbits?

I'm getting two separate error messages that have occurred at different times during the download. `bug_output1.txt` has happened twice now at the same point (67/82) and `bug_output2.txt` has happened once so far right towards the end of the download queue. Having a look at the IncompleteRead bug, I think it might be due to trying to download large amounts of data at once (see: https://github.com/Kydlaw/pumpy/issues/1, https://github.com/tweepy/tweepy/issues/908).

**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS: Linux Mint - Docker (pechnkov/pygmtsar tag: latest)

**Log 
[bug_output1.txt](https://github.com/AlexeyPechnikov/pygmtsar/files/15022259/bug_output1.txt)
file**
[bug_output2.txt](https://github.com/AlexeyPechnikov/pygmtsar/files/15022260/bug_output2.txt)

[For additional support, consider using the ChatGPT4-based InSAR AI Assistant at https://insar.dev/ai. It can provide guidance and help with understanding PyGMTSAR's capabilities and troubleshooting issues.]

**Comment by AlexeyPechnikov** [comment]
The error can be related to your own internet connection issues. And you need to download your dataset only once in a Docker container.

**Comment by benwright-davra** [comment]
Hi, thanks for the reply - i'm still having issues every now and then when downloading data. I've had another "max tries exceeded, connection refused" error (see above bug_output_2.txt) and as of today a new one (see below). I usually have around 70-90 Mbps and the connection is wired via ethernet. Are all these still likely to be related to my internet speeds? Thanks in advance. 
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/146717465/5c330666-50e8-45ed-9bc4-d96b646614d0)

**Comment by AlexeyPechnikov** [comment]
The noted ‘500 Server Error’ is obviously a server-side issue and is not related to your internet connection at all.

**Comment by benwright-davra** [comment]
Sorry, I'm still getting used to HTTP codes - I can't find anything relating to any news of server downtime (I've asked on their forum just in case). Would it be better to put the asf download into some sort of try statement in case something like this occurs again? I'll be downloading new scenes as they become available so there's more chances for something to go wrong.

**Comment by AlexeyPechnikov** [comment]
Yes, you can split your downloading into two parts: one for the older scenes and one for the most recent ones, wrapped in a try-catch block. The default behavior is to stop on downloading errors because we assume the processing results can be incorrect otherwise.
