### ISSUE TITLE
[Help]: Key error : ref; during sbas_pair()

### ISSUE THREAD

**Issue by mbahmu25** [mobigroup/gmtsar#127]
why is this happened ?
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/f625ed81-e0e8-4675-8573-53a144423f1b)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/2541a516-f761-4b89-976c-8f42967b80d5)

**Comment by AlexeyPechnikov** [comment]
Do you use the function for a single scene maybe?

**Comment by mbahmu25** [comment]
no, in these code i take it from lake sarez 2017 template, and i only cahnge the POI, scenes, and reference

**Comment by AlexeyPechnikov** [comment]
Please show your scenes list.

**Comment by mbahmu25** [comment]
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/fdee3ff7-adae-4a27-9435-9cb3ad6285c6)

**Comment by AlexeyPechnikov** [comment]
I mean your Stack.df scenes list. Typically, it is ‘sbas.df’ object.

**Comment by mbahmu25** [comment]
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/3a6e8678-5d41-4edd-9991-f817ea3a8623)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/e6c31ad1-f0c6-43ba-b03e-0ebf5146c606)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/bd729b86-1a09-4514-81f0-c28cdf44a373)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/c6bafcee-fa0b-433d-9e85-2ad4c2601320)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/58099250/1dee6250-bc09-4fc0-933c-bca9bb7f2103)

**Comment by AlexeyPechnikov** [comment]
Ok, I see the issue now. You have very sparse Sentinel-1 scenes with an interval between them about half a year, but tried to construct pairs with an interval of just 30 days. Obviously, that's impossible.

**Comment by mbahmu25** [comment]
Thankyou for your help, it works
