### ISSUE TITLE
[Help]: implenting stack of unwrapped interfrograms and coherence files from other SAR sensors to PyGMTSAR

### ISSUE THREAD

**Issue by soroushyasini** [mobigroup/gmtsar#133]
hi, i previously asked for adding ENVISAT support as you may remember.
i already made my stack of unwraped interferograms ( unwrap_ll.grd) and coherecne ( corr_ll.grd) by using GMTSAR software. you may know that the classic gmtsar SBAS algorithm is not good at all, so i want to use Pygmtsar as my time-sries analyzer.
the thing is how to load my stack into this program? i rode the code but i need some help.
any suggestion ?

**Comment by AlexeyPechnikov** [comment]
You might load GMTSAR processed phase and correlation grids in radar or geographic coordinates using xarray functions and form a compatible stack with the ‘pair’ dimension to apply PyGMTSAR functions. Optionally, you need to generate geocoding matrices to use PyGMTSAR geocoding. However, be aware that GMTSAR phase and correlation calculations are inaccurate (with approximately 30% error in phase and smoothed correlation), and the grids and geocoding processing are not pixelwise precise. In summary, if you don’t care about accuracy, it would be relatively simple. However, if you need to perform PSI or high resolution SBAS analyses, GMTSAR-processed results are not suitable.

**Comment by soroushyasini** [comment]
I see, it seems there are no other options for me since PyGMTSAR do not support Envisat processing from scratch (at least for now).
can you provide me a little bit more about how to load my data ( Envisat stack) into PyGMTSAR ?

**Comment by AlexeyPechnikov** [comment]
You can modify the PyGMTSAR function `open_stack()` to use `xr.open_mfdataset()` for opening multiple GMTSAR NetCDF grids by a specified path template and convert them into a 3D stack with the ‘pair’ dimension. The easiest approach seems to be using already geocoded grids.
```
    def open_stack(self, name, stack=None):
        """
        ...
        """
        import xarray as xr
        import pandas as pd
        import numpy as np
        import glob

        if stack is None:
            # look for all stack files
            #filenames = self.get_filenames(['*'], name)[0]
            #filenames = self.get_filename(f'{name}_????????_????????')
            # like data_20180323.grd or intf60m_20230114_20230219.grd
            filenames = self._glob_re(name + '_[0-9]{8}(_[0-9]{8})*.grd')
        elif isinstance(stack, (list, tuple, np.ndarray)) and len(np.asarray(stack).shape) == 1:
            # dates
            filenames = self.get_filenames(np.asarray(stack), name)
        else:
            # pairs
            filenames = self.get_filenames(stack, name)
        #print ('filenames', filenames)

        data = xr.open_mfdataset(
            filenames,
            engine=self.netcdf_engine,
            chunks=self.chunksize,
            parallel=True,
            concat_dim='stackvar',
            combine='nested'
        )

        # ...

        for dim in ['pair', 'date']:
            if dim in data.coords:
                if data[dim].shape == ():
                    data = data.rename({'stackvar': dim})
                else:
                    data = data.swap_dims({'stackvar': dim})

        # convert string (or already timestamp) dates to dates
        for dim in ['date', 'ref', 'rep']:
            if dim in data.dims:
                if not data[dim].shape == ():
                    data[dim] = pd.to_datetime(data[dim])
                else:
                    data[dim].values = pd.to_datetime(data['date'].values)

        return data
```
