### ISSUE TITLE
unable to open  DEM file

### ISSUE THREAD

**Issue by mhotalebi** [mobigroup/gmtsar#136]
thanks for responding my problems. recently I wanna runs my pygmtsar models in another cloud. but when i run it cant access to DEM file. I search issues and find someone had problem like me but I cant figure out how to fix it. because i cant find geoid_egm96_icgem.grd to create a symlink. (https://github.com/AlexeyPechnikov/pygmtsar/issues/124)
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/tmp/build/GMTSAR/share/gmtsar/geoid_egm96_icgem.grd', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by AlexeyPechnikov** [comment]
You can try to find it on your disk with the command:
```
find / -name geoid_egm96_icgem.grd
```
Alternatively, you can download the file from https://github.com/gmtsar/gmtsar/raw/master/gmtsar/geoid_egm96_icgem.grd and copy or symlink it to the expected location.

**Comment by mhotalebi** [comment]
thanks
