### ISSUE TITLE
[Bug]: Error with asf.download_scenes in Collab notebook 

### ISSUE THREAD

**Issue by JoeLydon** [mobigroup/gmtsar#139]
**Describe the bug**
When running the Türkiye_Earthquakes_2023.ipynb in Google Collab, I am getting an assertion error.

**To Reproduce**
- Open Türkiye_Earthquakes_2023.ipynb in Google Collab
- Run cells until asf.download_scenes code block

**Screenshots**
Code Block: 
![Screenshot 2024-06-10 101909](https://github.com/AlexeyPechnikov/pygmtsar/assets/77614346/8e7369db-fd54-41c6-b851-094bc90f78c9)

Error: ![Screenshot 2024-06-10 101713](https://github.com/AlexeyPechnikov/pygmtsar/assets/77614346/0ad9600f-127a-4dad-b2e5-fd47cb33ac54)

**System and software version:**
 - OS: Windows 11
 - PyGMTSAR version: 2024.6.3

**Processing Log**
Error Log: 
ASF Downloading Sentinel-1 SLC::  67%
 8/12 [00:10<00:42, 10.52s/it]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py", line 148, in download_scene
    assert os.path.getsize(fullname + '.tmp') == filesize, \
AssertionError: ERROR: Downloaded incomplete scene content
"""

The above exception was the direct cause of the following exception:

AssertionError                            Traceback (most recent call last)
[<ipython-input-16-c5e32b0ca12b>](https://localhost:8080/#) in <cell line: 4>()
      2 asf = ASF(asf_username, asf_password)
      3 # Optimized scene downloading from ASF - only the required subswaths and polarizations.
----> 4 print(asf.download_scenes(DATADIR, SCENES, SUBSWATH))

6 frames
[/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py](https://localhost:8080/#) in download_scenes(self, basedir, scenes, subswaths, polarization, session, n_jobs, skip_exist)
    163         # download scenes
    164         with self.tqdm_joblib(tqdm(desc='ASF Downloading Sentinel-1 SLC:', total=len(scenes_missed))) as progress_bar:
--> 165             joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(download_scene)\
    166                                     (scene, subswaths, polarization, basedir, session) for scene in scenes_missed)
    167 

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in __call__(self, iterable)
   2005         next(output)
   2006 
-> 2007         return output if self.return_generator else list(output)
   2008 
   2009     def __repr__(self):

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _get_outputs(self, iterator, pre_dispatch)
   1648 
   1649             with self._backend.retrieval_context():
-> 1650                 yield from self._retrieve()
   1651 
   1652         except GeneratorExit:

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _retrieve(self)
   1752             # worker traceback.
   1753             if self._aborting:
-> 1754                 self._raise_error_fast()
   1755                 break
   1756 

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _raise_error_fast(self)
   1787         # called directly or if the generator is gc'ed.
   1788         if error_job is not None:
-> 1789             error_job.get_result(self.timeout)
   1790 
   1791     def _warn_exit_early(self):

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in get_result(self, timeout)
    743             # callback thread, and is stored internally. It's just waiting to
    744             # be returned.
--> 745             return self._return_or_raise()
    746 
    747         # For other backends, the main thread needs to run the retrieval step.

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _return_or_raise(self)
    761         try:
    762             if self.status == TASK_ERROR:
--> 763                 raise self._result
    764             return self._result
    765         finally:

AssertionError: ERROR: Downloaded incomplete scene content

**Comment by AlexeyPechnikov** [comment]
This means exactly what is printed: ‘ERROR: Downloaded incomplete scene content,’ i.e., the scenes are not downloaded completely, and the processing is not possible. This can be due to network issues or problems with the Alaska Satellite Facility (ASF) servers. You can restart the notebook or limit the number of parallel downloads (n_jobs=1) and rerun:
```
asf.download_scenes(DATADIR, SCENES, SUBSWATH, n_jobs=1)
```

**Comment by JoeLydon** [comment]
@AlexeyPechnikov Thank you very much, that solved the issue.
