### ISSUE TITLE
[Help]: corr_sbas_stack = sbas.sync_cube(corr_sbas_stack, 'corr_sbas_stack') command is stuck

### ISSUE THREAD

**Issue by Aragon-yggdrasill** [mobigroup/gmtsar#145]
**Describe the problem you encountered**
Provide a brief description of the issue you're facing.
corr_sbas_stack = sbas.sync_cube(corr_sbas_stack, 'corr_sbas_stack') command is stuck, RAM only takes up 4.0g, and the progress bar always shows 0
**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS: colab pro
- PyGMTSAR version: 

**Steps to reproduce the problem**
If possible, describe how the problem can be reproduced from scratch. Include any commands or steps you took leading up to the issue.
29 scenes, one strip, the range is [[[103.1601, 31.3135], [103.4621, 31.3135], [103.4621, 31.5629], [103.1601, 31.5629], [103.1601, 31.3135]]], about 794.95 square kilometers
**Log file**
If you have a log file or terminal output related to the problem, please attach it here.

**Screenshot**
If applicable, attach a screenshot to help us better understand your situation.
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/161333390/d3796ac2-b19a-4042-b6be-7fe660aea879)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/161333390/5c033980-05d0-44bc-81f5-c63cb5c2f7b6)
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/161333390/d649f32f-24dd-4e27-9cc4-25403f12eb1c)

**Note**
- If you have a general question not directly related to PyGMTSAR, consider using the discussions page.

[For additional support, consider using the ChatGPT4-based InSAR AI Assistant at https://insar.dev/ai. It can provide guidance and help with understanding PyGMTSAR's capabilities and troubleshooting issues.]

**Comment by Aragon-yggdrasill** [comment]
PyGMTSAR SBAS and PSI Analyses: Lake Sarez Landslides, Tajikistan, this example

**Comment by AlexeyPechnikov** [comment]
I suppose your backend is disconnected. I’ve executed the notebook right now without issues:

<img width="1920" alt="image" src="https://github.com/AlexeyPechnikov/pygmtsar/assets/7342379/c4b2f549-c989-452c-8b8a-a2f755a28cac">

**Comment by Aragon-yggdrasill** [comment]
Thanks for your reply, I will try to change the WiFi

**Comment by Aragon-yggdrasill** [comment]
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/161333390/e0e4d7f8-3db7-4275-9349-94dacec9f66d)
