### ISSUE TITLE
[Help]: How to resolve Dask ValueError error in sbas.conncomp_main function in PyGMTSAR

### ISSUE THREAD

**Issue by Aragon-yggdrasill** [mobigroup/gmtsar#146]
**Describe the problem you encountered**
Provide a brief description of the issue you're facing.
Dear Mr. AlexeyPechnikov, I have a problem with processing data using the sbas.conncomp_main function of the PyGMTSAR library. When calling the function, I get a ValueError error related to Dask's multidimensional array chunking. I am not sure how to solve this problem.
**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS:
- PyGMTSAR version:

**Steps to reproduce the problem**
If possible, describe how the problem can be reproduced from scratch. Include any commands or steps you took leading up to the issue.

**Log file**
If you have a log file or terminal output related to the problem, please attach it here.

**Screenshot**
If applicable, attach a screenshot to help us better understand your situation.
![image](https://github.com/AlexeyPechnikov/pygmtsar/assets/161333390/afa6aa12-884b-4e43-a8fc-f185f9df839f)

**Note**
- If you have a general question not directly related to PyGMTSAR, consider using the discussions page.

[For additional support, consider using the ChatGPT4-based InSAR AI Assistant at https://insar.dev/ai. It can provide guidance and help with understanding PyGMTSAR's capabilities and troubleshooting issues.]

**Comment by AlexeyPechnikov** [comment]
You could omit this function call if you’re unsure about its usage. It’s typically employed to eliminate unconnected components in unwrapped phases, thereby preserving only the areas that are consistently unwrapped.

**Comment by Aragon-yggdrasill** [comment]
Thank you for your reply, Dear Mr. AlexeyPechnikov
