### ISSUE TITLE
[Help]: problem in sbas.plot_scenes(AOI=AOI)

### ISSUE THREAD

**Issue by jie666-6** [mobigroup/gmtsar#155]
**Describe the problem you encountered**
I followed the LakeSarez_Landslides_2017 while using my own S1 data. I got some problem when it comes to the step 
sbas.plot_scenes(AOI=AOI)

Traceback (most recent call last):
  File "/home/workdir/06_InSAR/code/exmaples.py", line 186, in <module>
    sbas.plot_scenes(AOI=AOI)
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/pygmtsar/Stack.py", line 140, in plot_scenes
    self.plot_AOI(**kwargs)
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/pygmtsar/Stack.py", line 96, in plot_AOI
    geometry[boundaries.is_empty].plot(ax=ax, color=boundary_color)
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/geopandas/plotting.py", line 968, in __call__
    return plot_dataframe(data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/geopandas/plotting.py", line 664, in plot_dataframe
    ax.set_aspect(1 / np.cos(y_coord * np.pi / 180))
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 1667, in set_aspect
    raise ValueError("aspect must be finite and positive ")
ValueError: aspect must be finite and positive 

**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS: Linux 
        Distributor ID: Ubuntu
        Description: Ubuntu 22.04.3 LTS
        Release: 22.04
        Codename: jammy
- PyGMTSAR version:  pygmtsar 2024.7.14.post2

**Steps to reproduce the problem**
I followed all steps in ' LakeSarez_Landslides_2017.ipynb'

**Screenshot**
I checked my AOI file and also the downloaded DEM, it seems that they are covering the same areas.
![image](https://github.com/user-attachments/assets/cd3909e8-4748-48d2-aedc-c2f087699403)

And all S1 is are downloaded using asf_research, both VV and VH, 123 subswath are downloaded at once.

So I am wondering what the problem is here.

Thanks in advance

[For additional support, consider using the ChatGPT4-based InSAR AI Assistant at https://insar.dev/ai. It can provide guidance and help with understanding PyGMTSAR's capabilities and troubleshooting issues.]

**Comment by AlexeyPechnikov** [comment]
Use PyGMTSAR tools to download scenes (bursts), DEM and orbits to be sure in their validity.

**Comment by jie666-6** [comment]
PyGMTSAR tools to download DEM and orbits work for me. But when I try to use it to download scenes,
it always show FileNotFoundError as following

![image](https://github.com/user-attachments/assets/7dca0f17-e3ef-4f63-a7ab-9907dda20388)


Here is the code I use

    # Set these variables to None and you will be prompted to enter your username and password below.
    asf = ASF(asf_username, asf_password)
    # Optimized scene downloading from ASF - only the required subswaths and polarizations.
    if SCENES is not None:
        print(asf.download_scenes(DATADIR, SCENES, SUBSWATH))

I still do not find the reason behind

**Comment by AlexeyPechnikov** [comment]
It seems your DATADI does not exist.

**Comment by jie666-6** [comment]
The DATADIR already exists. It always starts to download two scenes at the same time but it can only create the folders while all data cannot be successfully downloaded.
![image](https://github.com/user-attachments/assets/9f0a8298-d83d-4919-8d5f-b55029579ea2)
One subswath of one scene can be downloaded 
![image](https://github.com/user-attachments/assets/d73c6e48-3628-4c60-8e82-9e888b80e996)
As you can see in the figure above, the S1A_IW_SLC__1SDV_20170929T122249_20170929T122319_018590_01F56C_7698.SAFE/measurement/s1a-iw1-slc-vv-20170929t122249-20170929t122317-018590-01f56c-004.tiff has already been downloaded so the tmp file was deleted automatically.

**Comment by AlexeyPechnikov** [comment]
Try Python 3.10 as on Google Colab (and I use this release too). There are multiple libraries incompatible with the recent Python releases 3.11+.

**Comment by jie666-6** [comment]
I change python to 3.10.12 and use the pygmtsar latest version (pygmtsar 2024.8.2) and download all the data using pygmtsar tools. But still, I have the same problem

![image](https://github.com/user-attachments/assets/9e9564e8-ab0e-4691-846e-029084442fac)

**Comment by AlexeyPechnikov** [comment]
In this case try to plot sbas.plot_scenes() without the area of interest geometry.

**Comment by jie666-6** [comment]
Finally. It is the problem of Json file I created. If I typed the coordinates as the tutorial, it can be shown correctly. But if I read the information from a json file, I got such error.

**Comment by athifsayyaf** [comment]
I am having the same error.what was the changes you made?. Please let me know , where should i change in the json file??

**Comment by AlexeyPechnikov** [comment]
@athifsayyaf 
> Please let me know , where should i change in the json file??

You can embed your JSON into your notebook cell as shown in the examples. When you read the same JSON from a file, its structure can differ, and you need to check it and adopt your code accordingly. If you are not sure how to do it, just insert JSON directly into the notebook.
