### ISSUE TITLE
[Help]: issue in sbas.compute_align

### ISSUE THREAD

**Issue by jie666-6** [mobigroup/gmtsar#156]
**Describe the problem you encountered**
 When I run the code below
     if os.path.exists('/.dockerenv') and not 'google.colab' in sys.modules:
    # use special joblib backend in Docker containers
        sbas.compute_align(joblib_aligning_backend='threading')
    else:
        sbas.compute_align()

I got error message that 'make_s1a_tops' cannot find
 
![image](https://github.com/user-attachments/assets/9a5467af-cbf3-4611-893f-cc7c5886f946)

**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS: Ubuntu
- PyGMTSAR version: pygmtsar 2024.7.14.post2

I do not know if there is any step I miss or what should I do?

Thanks in advance

[For additional support, consider using the ChatGPT4-based InSAR AI Assistant at https://insar.dev/ai. It can provide guidance and help with understanding PyGMTSAR's capabilities and troubleshooting issues.]

**Comment by AlexeyPechnikov** [comment]
It means GMTSAR binaries do not installed. Check PyGMTSAR example notebooks and Dockerfile for the installation commands.

**Comment by jie666-6** [comment]
I try to use download the pygmtsar-large Image for the software installtion. Since I need to install it in our server where I do not have the sudo permission, I cannot install the dockerdesktop to our server directly and I just pull the image and create my own container in this case. But it seems that PyGMTSAR has not been installed completely. I can import pygmtsar but other functions such as S1, stack, etc are missing

Here is the command line I used for installation
docker pull mobigroup/pygmtsar-large
docker run -it -v /home/user/workdir:/home/workdir --shm-size=10g --gpus all  --user root -e GRANT_SUDO=yes --name user_pygmtsar-large-sudo [docker.io/mobigroup/pygmtsar-large](http://docker.io/mobigroup/pygmtsar-large) /bin/bash

And here is the error I got
![image](https://github.com/user-attachments/assets/f4798abd-312f-4149-af1f-03428b960f39)

I checked the installation path and it seems that there are a lot of files missing
![image](https://github.com/user-attachments/assets/7be173a3-9627-4dac-87bb-62b83afa2bfd)


I am not sure which step I might have gotten wrong in this case

**Comment by AlexeyPechnikov** [comment]
Pay attention to the first line of the image description:

> The Docker image provides PyGMTSAR 2023 version which supports only SBAS InSAR. The new PyGMTSAR, supporting both SBAS and PSI interferometry, is available in the Docker image [PyGMTSAR (Python InSAR) - Easy and Fast Satellite Interferometry For Everyone](https://hub.docker.com/r/mobigroup/pygmtsar).

**Comment by jie666-6** [comment]
Now it works. But I got another warning when I run sbas.compute_align().

![image](https://github.com/user-attachments/assets/32c1bcd2-6804-407a-8cbf-433587227b4d)

I use client.close() to free up resources and clearing out my Dask client before  sbas.compute_align() but it still show such warning

**Comment by AlexeyPechnikov** [comment]
Don’t worry about such warnings; they are mostly relevant for library developers. They can be produced by minor inconsistencies in your installed Dask, distributed, and other libraries. On Google Colab, we sometimes see many similar warnings and other times none. Python and its libraries are rapidly developing, but most of the time, even large-scale processing remains stable despite the warnings.

**Comment by AhmedDhahir** [comment]
I have a similar error with docker version. I thought the docker will have a complete installation but the error is the same as that I had form the locally installed version. here is the complete error message: --------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py#line=462), in _process_worker
    r = call_item()
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py#line=290), in __call__
    return self.fn(*self.args, **self.kwargs)
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 598](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=597), in __call__
    return [func(*args, **kwargs)
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 598](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=597), in <listcomp>
    return [func(*args, **kwargs)
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py", line 87](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py#line=86), in _reframe_subswath
    self._make_s1a_tops(subswath, date, debug=debug)
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe_gmtsar.py", line 120](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe_gmtsar.py#line=119), in _make_s1a_tops
    p = subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding='utf8', cwd=self.basedir)
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/subprocess.py", line 971](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/subprocess.py#line=970), in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/subprocess.py", line 1863](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/subprocess.py#line=1862), in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'make_s1a_tops'
"""

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
Cell In[19], line 1
----> 1 sbas.compute_reframe()

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py:340](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py#line=339), in Stack_reframe.compute_reframe(self, geometry, n_jobs, queue, caption, **kwargs)
    338     loky.get_reusable_executor(kill_workers=True).shutdown(wait=True)
    339 with self.tqdm_joblib(tqdm(desc=chunk_caption, total=len(chunk)*len(subswaths))) as progress_bar:
--> 340     chunk_records = joblib.Parallel(n_jobs=n_jobs, backend=joblib_backend)(joblib.delayed(self._reframe_subswath)\
    341                     (subswath, date,
    342                     geometry.intersection(geometries[subswath]) if geometry is not None else geometries[subswath],
    343                     **kwargs) for date in chunk for subswath in subswaths)
    344     records.extend(chunk_records)
    345 counter += len(chunk)

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:2007](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=2006), in Parallel.__call__(self, iterable)
   2001 # The first item from the output is blank, but it makes the interpreter
   2002 # progress until it enters the Try[/Except](http://localhost:8888/Except) block of the generator and
   2003 # reaches the first `yield` statement. This starts the asynchronous
   2004 # dispatch of the tasks to the workers.
   2005 next(output)
-> 2007 return output if self.return_generator else list(output)

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:1650](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=1649), in Parallel._get_outputs(self, iterator, pre_dispatch)
   1647     yield
   1649     with self._backend.retrieval_context():
-> 1650         yield from self._retrieve()
   1652 except GeneratorExit:
   1653     # The generator has been garbage collected before being fully
   1654     # consumed. This aborts the remaining tasks if possible and warn
   1655     # the user if necessary.
   1656     self._exception = True

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:1754](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=1753), in Parallel._retrieve(self)
   1747 while self._wait_retrieval():
   1748 
   1749     # If the callback thread of a worker has signaled that its task
   1750     # triggered an exception, or if the retrieval loop has raised an
   1751     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1752     # worker traceback.
   1753     if self._aborting:
-> 1754         self._raise_error_fast()
   1755         break
   1757     # If the next job is not ready for retrieval yet, we just wait for
   1758     # async callbacks to progress.

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:1789](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=1788), in Parallel._raise_error_fast(self)
   1785 # If this error job exists, immediately raise the error by
   1786 # calling get_result. This job might not exists if abort has been
   1787 # called directly or if the generator is gc'ed.
   1788 if error_job is not None:
-> 1789     error_job.get_result(self.timeout)

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:745](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=744), in BatchCompletionCallBack.get_result(self, timeout)
    739 backend = self.parallel._backend
    741 if backend.supports_retrieve_callback:
    742     # We assume that the result has already been retrieved by the
    743     # callback thread, and is stored internally. It's just waiting to
    744     # be returned.
--> 745     return self._return_or_raise()
    747 # For other backends, the main thread needs to run the retrieval step.
    748 try:

File [~/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py:763](http://localhost:8888/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py#line=762), in BatchCompletionCallBack._return_or_raise(self)
    761 try:
    762     if self.status == TASK_ERROR:
--> 763         raise self._result
    764     return self._result
    765 finally:

FileNotFoundError: [Errno 2] No such file or directory: 'make_s1a_tops'


it would be really helpful if you could help me resolve this issue.
Many thanks in advanced

**Comment by AlexeyPechnikov** [comment]
> File "[/home/ahmed/.conda/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py"

There is no such path in the Docker images, and this is your local home directory on your local system: "/home/ahmed/"
