### ISSUE TITLE
[Help]: error in geocoding

### ISSUE THREAD

**Issue by jie666-6** [mobigroup/gmtsar#157]
I followed all steps in LakeSarez_Landslides_2017.ipynb  using different study site as following

![image](https://github.com/user-attachments/assets/c7a538c9-2b6e-42f3-891c-4ce2e7a59953)

when it comes to  sbas.compute_geocode(10.)

I got such error. Do you know what the problem is here?
![image](https://github.com/user-attachments/assets/6b813f72-9450-4ba9-9e9b-c73d9d63a663)

**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
OS: Ubuntu
PyGMTSAR version: pygmtsar 2024.7.14.post2

**Comment by AlexeyPechnikov** [comment]
It seems your DEM doesn’t cover the area and so geocoding is not possible. Enlarge your DEM extent and try again.

**Comment by jie666-6** [comment]
GLO30 does not provides the DEM covering those areas since it is ocean instead of land. 
![image](https://github.com/user-attachments/assets/7ae2614f-8474-46d0-a06a-b9a7595eeec0)


Then I choose the SRTM which covering entire AOI instead. 
Then when it comes to the sbas.compute_reframe(AOI), only a small part of S1 can be shown in this plot

![image](https://github.com/user-attachments/assets/9e392a92-7d70-424d-93c7-2f34b52c5e57)

I am wondering why it plot like this
