### ISSUE TITLE
datagrid and sbas.find_pairs couldn't imported

### ISSUE THREAD

**Issue by Meysam-Amiri** [mobigroup/gmtsar#17]
Hi @mobigroup, I am trying to run the SBAS on my data and on my local computer using the Yamchi_dam notebooks. I face these errors in importing some modules. I ignored that part and created Interferograms and saved a backup file. Like the second notebook I am trying to restore the saved pickle and use find_pairs but it seems that there is no attribute for that. Any idea for solving these issues?
**OS and software version**
OS: Ubuntu 20.04.3 LTS
GMTSAR version: master

**Log file**
`from pygmtsar import datagrid`
`datagrid.chunksize = 1024`
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [8], line 3
      1 # default chunksize (512) is enough suitable for a single subswath processing using resolution 15m
      2 # select higher chunk size (1024) to process multiple subswaths and scenes using resolution 15m
----> 3 from pygmtsar import datagrid
      4 datagrid.chunksize = 1024
ImportError: cannot import name 'datagrid' from 'pygmtsar' (/home/meysam/.local/lib/python3.8/site-packages/pygmtsar/__init__.py)

`pairs = sbas.find_pairs()`
`pairs`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [11], line 1
----> 1 pairs = sbas.find_pairs()
      2 pairs
AttributeError: 'SBAS' object has no attribute 'find_pairs'.

**Comment by mobigroup** [comment]
What PyGMTSAR version do you use? Check it as below:

```
pip3 show pygmtsar
Name: pygmtsar
Version: 2022.12.1
```

**Comment by Meysam-Amiri** [comment]
I noticed that my PyGMTSAR version was old and I have updated it with `python3 setup.py install` using the directory of pygmtsar. Thanks for your help.

**Comment by Meysam-Amiri** [comment]
In plotting it seems that I don't have the turbo colormap. I couldn't figure out how to add it! I have changed it to rainbow.
[error_cmap.txt](https://github.com/mobigroup/gmtsar/files/10275483/error_cmap.txt)

**Comment by mobigroup** [comment]
The colormap available in modern Python versions like to 3.10. In the basic PyGMTSAR examples ‘turbo’ colormap is not used because it’s not available on Google Colab.

**Comment by Meysam-Amiri** [comment]
@mobigroup, I have processed my data thanks to Yamchi_dam notebooks. How can I improve the results so they wouldn't be like separate pixels in the last sbas map? Does it depend on the resolution that we define or chunk_size?
One more question, How can I get the time series of a point? Is there any example in notebooks?
Here are my notebooks:
https://drive.google.com/drive/folders/1hpCkLDqMV_lqgYUAnzfJAMn-OiiBUNUl?usp=sharing
Thanks a lot.

**Comment by mobigroup** [comment]
@Meysam-Amiri I think you'd use mask with zeroed area for y<5000 instead of composite_mask for unwrapping. On your results we see some phase discontinuity below y=5000 due to decorrelation:
![image](https://user-images.githubusercontent.com/7342379/210161572-a7adeaaf-5e4d-49a2-a095-6f4e4873ed7e.png)

Pixels are sparse because of correlation stack mask applied (corr_mask) and we are able 1) exclude it for SBAS processing or 2) fill the gaps after unwrapping using nearest interpolation. For your area the both ways look suitable.

We can define the manual mask like to
```
manual_mask = (corrs[0].where(corrs.y >= 5000)>=0).astype(bool).persist()
```

and use it for unwrapping as
```
sbas.unwrap_parallel(mask=manual_mask, conf=conf, n_jobs=...)
```
