### ISSUE TITLE
ValueError in topo_ra_paralel()

### ISSUE THREAD

**Issue by ClassiCcOwl** [mobigroup/gmtsar#18]
Hi devs

There is a problem with the function **topo_ra_parallel()**
It raises an error :
ValueError: zero-size array to reduction operation maximum which has no identity

I've tested S1A_2016_Kumamoto_Earthquake_vs_ESA_Sentinel_1_Toolbox project in google Colab.

**Comment by mobigroup** [comment]
Fixed, please check the notebooks. The issue was related to upgraded Python 3.7 to 3.8 on Google Colab but with outdated numeric calculation libraries preinstalled.

**Comment by ClassiCcOwl** [comment]
Well done

It's fixed
