### ISSUE TITLE
[Bug]: Download failed for burst [] "noiseRangeVectorList"

### ISSUE THREAD

**Issue by MartinDanieau** [mobigroup/gmtsar#180]
**Describe the bug**
When trying to download a burst from 2017 or earlier, the asf.download(DATADIR, BURSTS) returns an error "Bursts downloading failed for X bursts". However the bursts is still downloaded but the files under the "annotation" folder are not created. After further research, it seams that the error is cause by the modification of the download_burst function introduced in version 2024.8.30.post4. When creating annotation files, the function try to read a "noiseRangeVectorList" from an XML file (see screenshot). However, in early S1 bursts XML files, only "noiseVectorList" is defined, causing the error.

**To Reproduce**
- Define Bursts from 2017 or before
- Download them using the asf.download(DATADIR, BURSTS)

This error can be found in the [Lake Sarez Landslide example notebook](https://colab.research.google.com/drive/1O3aZtZsTrQIldvCqlVRel13wJRLhmTJt?usp=sharing)

**Screenshots**

![image](https://github.com/user-attachments/assets/018bd7c1-0f22-4581-9b17-d2e7d42eaa7b)

![image](https://github.com/user-attachments/assets/8e1bcd72-99f3-464e-b3d6-9a424798e958)

**System and software version:**
 - OS: Linux (Google Colab Notebook)
 - PyGMTSAR version: 2024.8.30.post4

**Comment by AlexeyPechnikov** [comment]
Ok, fixed in today’s update.

**Comment by MartinDanieau** [comment]
Thank you very much !
