### ISSUE TITLE
[Help]: Init SBAS step error

### ISSUE THREAD

**Issue by Hassan2211345** [mobigroup/gmtsar#181]
**Describe the problem you encountered**
I encounter problem in Init SBAS step. Prior to that, everything went smooth. In error, it refereed to a resolved error which I checked but is unrelated to the problem I am facing...
Software versions:
Ubuntu version: Ubuntu 24.04.1 LTS
- Python: Python 3.12.4
- PyGMTSAR version: 2023.5.3

**Steps to reproduce the problem**
I run steps following the PyGMTSAR_Türkiye_Earthquakes_2023_01_29_2023_02_10_3scenes.ipynb Jupyter Notebook step by step. I tried various commands for Init SBAS step but failed in all cases. Also, every time I encountered this error, the downloaded tiff and xml files have been wiped away as well from the data directory. My data is from South Island of new Zealand

**Screenshot**
![Screenshot_2024-12-04_15-42-48](https://github.com/user-attachments/assets/062825ae-b47e-4550-84b7-4fd83a5b2af2)

Screenshot with the problem log is attached.

**Comment by AlexeyPechnikov** [comment]
It seems there is no data for processing, which is causing the error. Could it be that your DATADIR is the same as your WORKDIR?

**Comment by Hassan2211345** [comment]
Dear Alexey Pechnikov. Yes that's right. I made WORKDIR AND DATADIR different now and it worked. Before, they were in the same directory, like a folder within another folder.

Thanks a lot for your feedback.

Here is how I set my folders 
# Folders for processing to carry out. 
WORKDIR      = '/Users/home/science/Kaikoura-work'
DATADIR      = '/Users/home/science/Kaikoura-data'

and it worked, now SBAS is initialized.... :)

**Comment by Hassan2211345** [comment]
This issue is resolved.
