### ISSUE TITLE
Reframe : Stitching scenes

### ISSUE THREAD

**Issue by Hassan22113** [mobigroup/gmtsar#182]
Ubuntu version: Ubuntu 24.04.1 LTS
Python: Python 3.12.4
PyGMTSAR version: 2023.5.3

I am wondering how to set a code for stitching 2 scenes acquired on a particular date and along the same track with three subswaths in each scene. I already have orbit files. There are no pins (GDPs). If information on pins is not available,  how to set a code that sbas_reframe.py automatically stitch scenes.
I checked available notebooks but none have the code for the stitching. I run some codes but I get error that there are no pins defined.

I will appreciate any feedback on that :)

**Comment by AlexeyPechnikov** [comment]
Of course, there are examples of how to stitch scenes. You can refer to the notebook ‘CENTRAL Türkiye Mw 7.8 & 7.5 Earthquakes Co-Seismic Interferogram, 2023’ available at https://insar.dev

**Comment by Hassan22113** [comment]
Thanks a lot dear Alexey Pechnikov. Yes in the mentioned example, I found the code
sbas.compute_reframe() which will likely do it automatically.  Thanks a bunch :). I will give it a try in my office. Wish you a wonderful day...
