### ISSUE TITLE
Bugs : print(asf.download(DATADIR, SCENES, SUBSWATH)) print(asf.download(DATADIR, BURSTS))

### ISSUE THREAD

**Issue by farikahsm6** [mobigroup/gmtsar#183]
**Describe the bug**

**To Reproduce**

**Screenshots**

**System and software version:**
 - PyGMTSAR version:

**Processing Log**
If applicable, attach a log file from notebook cell or terminal output or relevant error messages

[Please note you can use the ChatGPT4-based InSAR AI Assistant for guidance or troubleshooting. Visit https://insar.dev/ai for more information.]

**Comment by farikahsm6** [comment]
I found an error in downloading data in ASF, do you have a solution? 
error
NameError                                 Traceback (most recent call last)
[<ipython-input-20-3726c9b67b18>](https://localhost:8080/#) in <cell line: 2>()
      1 # Set these variables to None and you will be prompted to enter your username and password below.
----> 2 asf = ASF(asf_username, asf_password)
      3 # Optimized scene downloading from ASF - only the required subswaths and polarizations.
      4 # Subswaths are already encoded in burst identifiers and are only needed for scenes.
      5 #print(asf.download(DATADIR, SCENES, SUBSWATH))

NameError: name 'ASF' is not defined
I have searched for some solutions myself but have not found the right answer for this error.

**Comment by AlexeyPechnikov** [comment]
The ASF module needs to be imported first, as demonstrated in the example notebooks available at [InSAR.dev](https://insar.dev/).
