### ISSUE TITLE
[Bug]: PyGMTSAR seems to be broken on the compute_ps step

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#184]
Hello Alexey,
I have tested multiple different datasets and they all fail at the compute_ps() funcition. I have tried reverting to an older version of PyGMTSAR and the problem persists. I think there might of been some dependency update such as dask that has broken the code. 

![image](https://github.com/user-attachments/assets/742e2930-5e24-4f64-9f17-8baa9ec0f559)

**Comment by SteffanDavies** [comment]
The problem lies in the latest version of dask.

Installing dask[complete]==2024.4.1 solves the error. The setup.py should be changed to limit dask version.

**Comment by AlexeyPechnikov** [comment]
Hi Steffan,

Thanks for the report and solution! I think it’s not feasible to pin the Dask version for PyGMTSAR since it behaves quite differently across platforms like Linux, macOS, etc.
