### ISSUE TITLE
 computational times for compute_reframe  step + error in compute_align

### ISSUE THREAD

**Issue by Hassan2211345** [mobigroup/gmtsar#185]
Greetings,
I want to mention about the issue i am facing. I am running sbas.compute_reframe() step and it is taking about 1 hour to complete. And it produces in my WORKDIR several redundant sentinel scene files (same as inputs in DATADIR) so many multiple times reaching >40GB. Although the step runs completely but it takes times and also generate heavy files in my workdir. I am not sure if there is something wrong I am doing or it is the expected output ?
Any guidance on that ?

Additionally, when I run sbas.compute_align(), I get this error as attached in 3rd photo. Reference alignment works and then fails in aligning repeat.

Scenes I am using are 
'S1A_IW_SLC__1SSV_20161103T072220_20161103T072250_013774_0161F9_2F68','S1A_IW_SLC__1SSV_20161103T072248_20161103T072317_013774_0161F9_E78A','S1B_IW_SLC__1SSV_20161121T072138_20161121T072207_003053_005313_8A72','S1B_IW_SLC__1SSV_20161121T072205_20161121T072240_003053_005313_ED7D','S1B_IW_SLC__1SSV_20161215T072137_20161215T072207_003403_005D05_09EF','S1B_IW_SLC__1SSV_20161215T072204_20161215T072240_003403_005D05_8F54'

Thanks a lot and looking forward to your feedback

My system details.
- Ubuntu: 24
-Python: 3.12
- pygmtsar==2024.8.30.post3:
Client: 'tcp://127.0.0.1:33173' processes=3 threads=12, memory=26.70 GiB

![reframe](https://github.com/user-attachments/assets/84cd6d13-bf01-4057-88c6-3a4342a63ab7)

![reframe2](https://github.com/user-attachments/assets/1019eec1-90ae-4476-b4b0-82e8c15bb3e7)
![align](https://github.com/user-attachments/assets/37225cfd-879a-43fb-ba0e-cd1ab5358c0d)

**Comment by AlexeyPechnikov** [comment]
> I am running sbas.compute_reframe() step and it is taking about 1 hour to complete. And it produces in my WORKDIR several redundant sentinel scene files (same as inputs in DATADIR)...

Reframing involves reorganizing your scenes and bursts into new scenes, which can range from just one burst to dozens, covering your processing area. If you’re processing a complete scene or a single burst, reframing may not be necessary.

> Python: 3.12

There are some incompatibilities between the required scientific libraries and Python 3.12, particularly when using the Anaconda installer with custom library builds. I recommend switching to Python 3.11 and using the PyPI libraries repository for better compatibility.

**Comment by Hassan22113** [comment]
Thanks a lot for the feedback. I am trying to stitch two scenes (including their bursts) for a larger area deformation map. However, for this attempt, I will focus on one complete scene and skip reframing. I will get back to you once I install the suggested python version and retry.

Thanks again 😇

**Comment by Hassan22113** [comment]
Hey there dear Alexey Pechnikov,

I setup a new environment with Python 3.11 and installed libraries from PiPl repositories.  Re run processing and this time the error is slightly different with the compute_align steps. I followed the steps correctly however it shows I need to set the DEM first. The DEM is downloaded already for the study area. I am wondering how to tackle this "Set DEM first" exception. 
Looking forward to your suggestion while I try different ways to handle it. Thanks

![error](https://github.com/user-attachments/assets/edef11f0-4a93-48a3-8dea-f21c1b96eb97)

**Comment by AlexeyPechnikov** [comment]
DEM downloading refers strictly to downloading the DEM and nothing more. To utilize the DEM in processing, it must be loaded using sbas.load_dem(DEM, AOI=...).

**Comment by Hassan22113** [comment]
Thanks you very much for your suggestions dear Alexey Pechnikov.

Yes I somehow missed loading the dem. It worked and the step overall progressed. 
I am closing the issue as resolved.
 
Takeaway (based on your advice):  Install Python 3.11 in a separate environment and then install all libraries using pip making sure that while they run, the path is pointing to the location of installed libraries in the new environment folder.
And then running all steps untill compute_align which will definitely work.

Cheers.
