### ISSUE TITLE
General issue regarding geocoding transform step

### ISSUE THREAD

**Issue by Hassan2211345** [mobigroup/gmtsar#190]
Hey there,

Coming with one more follow-up question.
When running geocode transform step (tried with RESOLUTION OPTION AS WELL), I get this error. In my understanding, the problem could be with the DEM. Part of the scene locates offshore and there are no DEM tiles there (Attached screenshots).

Would it be a solution to go for subswath 23 rather than 123 and skipping subswath 1? confirming here before proceeding for that. If that is not the problem, then the problem could be that I choose another dem, manually loaded? or anything else I might be missing here ?

Looking forward. 

![DEM](https://github.com/user-attachments/assets/c0debd57-57de-4907-88b3-7c7816fe2ab3)
![Geocode](https://github.com/user-attachments/assets/d8dfbca0-eb9f-4bea-8905-dcb89c6588c1)

**Comment by AlexeyPechnikov** [comment]
Definitely, the DEM should cover the entire processing area. You can fill the NODATA pixels with zeroes (for sea surfaces) or load an alternative DEM.

**Comment by Hassan2211345** [comment]
I changed NODATAVALUES to zero using a simple script. The DEM peripheral margins now looks like to covering completely the scene and the geocode transform begin to work. I get a warning (as attached) but the step completed successfully and now I am proceeding to next steps
Thanks....
![corrected dem](https://github.com/user-attachments/assets/98796469-1e75-4313-9250-8d65e6514382)

![trans](https://github.com/user-attachments/assets/1b9554f9-e178-4adf-868d-1dafbca78fcb)
