### ISSUE TITLE
Request for suggestions to deal with decorrelation in interferogram

### ISSUE THREAD

**Issue by Hassan22113** [mobigroup/gmtsar#192]
Hi there,
After running all the steps to interferogram, I generated correlation and interferogram maps

For phase and correlation, I used the parameters as followed:

topo = sbas.get_topo()
data = sbas.open_data()
intensity = sbas.multilooking(np.square(np.abs(data)), wavelength=400, coarsen=(4,16))
phase = sbas.phasediff(pairs, data, topo)
phase = sbas.multilooking(phase, wavelength=400, coarsen=(4,16))
corr = sbas.correlation(phase, intensity)
phase_goldstein = sbas.goldstein(phase, corr, 32)
intf = sbas.interferogram(phase_goldstein)
decimator = sbas.decimator(resolution=RESOLUTION, grid=intf)
tqdm_dask(result := dask.persist(decimator(corr), decimator(intf)), desc='Compute Phase and Correlation')
corr, intf = [grid[0] for grid in result]
intf

I am wondering if the interferogram could be improved tweaking some of these parameters. Looking forward to your suggestions and directions. Indeed most of the part of this sentinel 1 scene is offshore so thats understandable that we have zero amplitude there but part of the interferogram where the seismic event happen still have some decorrelation around.

Thank you:) dear  Alexey Pechnikov for your patience and advices, finally I have made it to an interferogram...

![Screenshot_20241213_212244_MobiOffice](https://github.com/user-attachments/assets/ce61c9aa-63b8-42ad-a859-10d3de38bdc7)
![Screenshot_20241213_212251_MobiOffice](https://github.com/user-attachments/assets/a155b407-135d-4567-9d20-f9d0695aa354)

**Comment by AlexeyPechnikov** [comment]
The interferogram appears usable, with fringes clearly detected. To enhance the results, consider applying a land mask to exclude water surface areas from the interferogram. It can enhance and speedup the unwrapping process.

**Comment by Hassan22113** [comment]
Thank you very much :), yes I am on it. Those are the steps i am going to be doing ahead. Have a nice day :)
