### ISSUE TITLE
Changing .nc DEM no data values to zero

### ISSUE THREAD

**Issue by Hassan2211345** [mobigroup/gmtsar#194]
HI there,

Last time while processing, I used a simple script to change no data values in dem (.nc) to 0 in order to cover the whole area of the scenes extent.
The script i run was following and it worked

import xarray as xr
import numpy as np
file_path = 'dem.nc'
output_path = 'dem_updated.nc'
ds = xr.open_dataset(file_path) # Load dem
ds['z'] = ds['z'].where(~np.isnan(ds['z']), 0)
ds.to_netcdf(output_path) # Save
print(f"Modified NetCDF file saved to {output_path}")

However, this time when I run again another processing, I tried this way and several other ways to change nodatavalues to zeros including using "jq" tool, but its failing again in geocode step with the same error that last time was solved with the above script.

Is there a nicer and more straight forward way to do it ? Thanks a alot.....
Also, when I try to use other DEM formats than .nc, it fails to process...Any comments on that ?

**Comment by AlexeyPechnikov** [comment]
Typically, this indicates that your DEM coverage is insufficient. As mentioned earlier, PyGMTSAR offers the ability to download three different DEMs with two resolution options (1 arcsecond ~30m and 3 arcseconds ~90m), allowing you to select a DEM that fully covers your area almost anywhere.

**Comment by Hassan22113** [comment]
Thanks.
Yes , 
fillna.(0) also solves the problem at the time of running the dem downloading code. Some issues with my system. Resolved already now. 
Thanks a bunch!
