### ISSUE TITLE
Step detrend fails: Error of overlapping depth > array size

### ISSUE THREAD

**Issue by Hassan2211345** [mobigroup/gmtsar#196]
Good day dear Alexey Pechnikov,

I run step unwrapping with the parameters as in the screenshot. However when I run the step detrend, I get an error of overlapping depth > array size as indicated in the screenshot.
I am finding it difficult to understand how to tackle this. What adjustments do I need in parameters to be able to run detrending step.

Thanks a bunch. Looking forward to hear from you

![detrend error](https://github.com/user-attachments/assets/57dbc122-5f2d-4753-895d-fe7580c9f29a)
![unwrap_parameters](https://github.com/user-attachments/assets/18ccc1f0-d43d-47d7-a343-64ae395680cf)
![size](https://github.com/user-attachments/assets/c48a43d1-8f5f-4c2e-9588-117044c5e2af)

**Comment by SteffanDavies** [comment]
Is your gaussian wavelength larger than your area?

**Comment by Hassan2211345** [comment]
Thanks for your reply, you mean the wavelength I specified (300000) is too large for the area 3616 x 4138? I am trying this from a notebook where area is much smaller and this wavelength is applied but over there it went without error. So I wanted to check how it works for me, but it gives this error.  I will try more shorter wavelengths. What do you suggest for  3616 x 4138 area ?

tqdm_dask(detrend := (unwrap.phase - sbas.gaussian(unwrap.phase, wavelength=**300000**)).persist(),
          desc='Detrending')

**Comment by Hassan2211345** [comment]
THis is what I get with 30,000
![detrend_phase_30000](https://github.com/user-attachments/assets/ac22e579-e3a9-40b2-8abd-80c73097284b)

**Comment by Hassan2211345** [comment]
Thanks..... As we increase the Gaussian wavelength, it gets better and better (until we exceed the size of our area where it gives error). I am closing this issue.

**Comment by AlexeyPechnikov** [comment]
Gaussian detrending is not the only detrending tool in PyGMTSAR. It is easy to use but not precise and has its limitations. Use precise tidal correction together with linear regression on the complete area or in chunks, and possibly pixel-wise residual topography correction for better results.

**Comment by Hassan2211345** [comment]
Thanks a lot for your insights dear Alexey Pechnikov. Sure, I will try those methods too...

**Comment by AlexeyPechnikov** [comment]
By the way, there is a parameter to define the filter window size: Stack.gaussian(..., truncate=3.0). By using truncate=2.0, the filter size can be reduced by 1.5x, allowing for the use of a 1.5x larger wavelength on the same raster. However, it’s important to carefully evaluate the accuracy of your results. Gaussian filtering does not inherently guarantee that the output will be valid, as it may filter out real signals.

**Comment by Hassan2211345** [comment]
> Gaussian detrending is not the only detrending tool in PyGMTSAR. It is easy to use but not precise and has its limitations. Use precise tidal correction together with linear regression on the complete area or in chunks, and possibly pixel-wise residual topography correction for better results.

Hi there, Is there a notebook or guidelines that are based on different detrending tools than the Gaussian detrending ? Just wondering and trying to apply better detrending tools. Have a nice day

**Comment by AlexeyPechnikov** [comment]
The ‘Trend Correction’ section is included in the examples 'PyGMTSAR SBAS & PSI: Golden Valley, CA' and 'PyGMTSAR SBAS & PSI: Lake Sarez Landslides, Tajikistan'. These examples are available at https://insar.dev/.

Additionally, lots of articles and examples are shared on my Patreon: https://www.patreon.com/c/pechnikov.

**Comment by Hassan22113** [comment]
Noted that. Thanks a lot
