### ISSUE TITLE
LOS displacement for SBAS

### ISSUE THREAD

**Issue by simonst7** [mobigroup/gmtsar#2]
Hello @mobigroup ,

Many thanks for this project. I've been trying to recreate the maps in my own OS (I use Fedora36 and everything goes well with the standard installation). 
I have a question how to generate the correct LOS displacement after processing sbas_parallel. 

It seems that in google colab example for S1A Stack are positive results 
![Cum_LOS_Displacement_googlecolab](https://user-images.githubusercontent.com/53209067/191354546-b2623edc-c285-4513-84a5-c904fc23b6eb.png)
But the deformation should be negative, right?. 

I tried to replicate that but I obtained positive results as well.
![Cum_LOS_Displacement](https://user-images.githubusercontent.com/53209067/191354825-30e43e49-719a-4e69-a012-24335220e29f.png)

the simplest solution is just multiplying the grid array by -1 because the values seem to make sense.

but I wanted to know if you know why the cumulative displacement is positive? or if I did something wrong.

Thanks in advance
 Simon

**Comment by simonst7** [comment]
I don't know why, but I could fixed that calculating the LOS like a separate function 
![image](https://user-images.githubusercontent.com/53209067/191409608-fea60e59-3197-43d2-939e-2df9a9fee18e.png)
instead of 
![image](https://user-images.githubusercontent.com/53209067/191409817-c1d66d3c-19ea-4c8c-a627-cb0901fccb11.png)

this is the new result:
![Cum_LOS_Displacement_fixed](https://user-images.githubusercontent.com/53209067/191409944-cfc9a1a6-5ed5-4121-9f04-bd93730b12a4.png)

**Comment by mobigroup** [comment]
@simonst7 Thanks, sure that's an error. Actually, the function applied twice. Fixed for now and PyPI library updated and Google Colab notebooks rerunned.
