### ISSUE TITLE
Regarding coherence

### ISSUE THREAD

**Issue by AmiraZakii** [mobigroup/gmtsar#20]
Hello Alexy, 
I have a general question, where can I control the coherence threshold? I found only this line related to coherence cleaner = lambda corr, unwrap: xr.where(corr>=CORRLIMIT, unwrap, np.nan), but it is not clear to me depends on what the software selects points as low coherence. Can you explain it, please?
Thank you

**Comment by mobigroup** [comment]
There are multiple ways explained in this notebook: https://github.com/mobigroup/YamchiDam/blob/main/notebooks/Yamchi_Dam_2_unwrap-large.ipynb Also, the pipeline including the notebook available in this large Docker image: https://hub.docker.com/r/mobigroup/pygmtsar-large
