### ISSUE TITLE
Timed out trying to connect to tcp://ip-addr-of-scheduler:8786 after 30 s

### ISSUE THREAD

**Issue by amrit-thapa-2044** [mobigroup/gmtsar#21]
**Describe the bug**
Hi i am going through ASF_Downloading_2020_Ardabil_Earthquake.ipynb and ended with the error "Timed out trying to connect to tcp://ip-addr-of-scheduler:8786 after 30 s' after I execute sbas.topo_ra_parallel() in Ubuntu 22.04.1 LTS. DO you have any suggestion to fix this issue.

**To Reproduce**

**Screenshots**
<img width="825" alt="pyGRMsar" src="https://user-images.githubusercontent.com/59821600/218249134-d001a42a-7ac6-4453-8492-d72340595080.PNG">

**System and software version:**
 - OS: Ubuntu 22.04.1 LTS
 - GMTSAR version:

**Processing Log**
If applicable, attach a log file from the terminal output

[Please note that if no new responses are made over six months from users, the issue will get closed. If the report involves a simple fix in the code, the change could be done quickly; if it involves developing new features, do expect them to be done over the long run. Under both cases, the report will remain open until the issue is addressed one way or another.]

**Comment by mobigroup** [comment]
It looks as Python library versions incompatibility. Try to upgrade your libraries or use PyGMTSAR Docker images with pre-configured environment.
