### ISSUE TITLE
[Help]:Installation help 

### ISSUE THREAD

**Issue by cxinlong** [mobigroup/gmtsar#22]
**Describe the problem you met**
I have installed docker desktop, but why can't I open it.

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![2023-02-17 13-18-46 的屏幕截图](https://user-images.githubusercontent.com/118950056/219556149-3d00150d-41b5-44e8-b9f9-05daaeed04df.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
Ubuntu is not so user-friendly system, especially outdated Ubuntu. It requires terminal usage to resolve different issues. In case your service is masked as noted above, just unmask it first like to:
```
sudo systemctl unmask docker-desktop
sudo systemctl start docker-desktop
```

**Comment by mobigroup** [comment]
On the screen above the SBAS notebook is already selected - just open and run it. And SBAS pipeline for a large dataset available in this Docker image: https://hub.docker.com/r/mobigroup/pygmtsar-large

**Comment by cxinlong** [comment]
I can't download pygmtsar-large because I don't have enough memory. So I deleted some files and redownloaded pygmtsar-large again, the progress bar kept running, but I couldn't download it. What's the reason?I remember the first download didn't take this long. And do I have to download pygmtsar again every time I reopen docker?
![2023-02-17 16-48-10 的屏幕截图](https://user-images.githubusercontent.com/118950056/219598088-3a319fba-dfca-4125-aa00-78618ab969e9.png)

**Comment by mobigroup** [comment]
pygmtsar-large is a large Docker image (50 GB) and it requires 500 GB disk space for the processing, see the information on your screen. In case when you work on SBAS timeseries you usually need a lot of disk space. FYI, a single Sentinel-1 scene size is about 4.5 GB (zipped).

**Comment by cxinlong** [comment]
Can I specify its installation path? The memory of the system is not that big. Can I install it on the hard disk?

**Comment by cxinlong** [comment]
I just downloaded pygmtsar-large. Halfway through the download, I ran out of memory in my home directory. I had 33G left, but now it's 0 bytes. I want to delete the pygmtsar-large download to free up memory in the home directory and make sure the docker starts. What should I do?

**Comment by mobigroup** [comment]
As I’ve noted above that’s easy to change the images location (on the same settings page as the resources limits), and for a complete Docker knowledge you need to read Docker documentation https://docs.docker.com/

**Comment by cxinlong** [comment]
I just don't know where the half-downloaded pygmtsar-large is stored, I can't find it, so I don't have enough memory in the home directory, so docker won't start. I don't know the solution to this problem now.

**Comment by mobigroup** [comment]
The common solution is to restart your Docker service and your computer to clean temp files.

**Comment by cxinlong** [comment]
Hello, I checked out notebooks and it seems that everything is filled with your data processing. If I want to use my data processing, how do I import my data? Also, I've already processed the necessary data with GMTSAR, now I just need to do the SBAS analysis. Can I start directly with the SBAS? Or do I just have to go back to step one?

**Comment by mobigroup** [comment]
> I checked out notebooks and it seems that everything is filled with your data processing.

Yes, sure, these are live notebooks for complete processing cases.

> If I want to use my data processing

Then use your data. All the details documented in the notebooks.

> I've already processed the necessary data with GMTSAR

That is possible while some programming required to rearrange the data. The complete processing is more straightforward.
