### ISSUE TITLE
[Help]: facing issue installing.Pygmtsar

### ISSUE THREAD

**Issue by shivamshuklaz** [mobigroup/gmtsar#25]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicabl
![WhatsApp Image 2023-03-13 at 4 55 10 PM](https://user-images.githubusercontent.com/75002574/224689166-d91c3c9d-3d9f-4f64-97eb-be9d264e7a40.jpeg)
 i am facing installing PYGMTSAR have motioned a snapshot, I have done multiple process  pull and run, what is the next step.., what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
Open "Containers" tab in Docker Desktop left vertical menu to found your running containers. Do you see this one or more here?
