### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory: 'senTest/F123_20150625_20150812_corr.PRM' -> 'senTest/S1_20150625_ALL_F123.PRM'

### ISSUE THREAD

**Issue by benwright151** [mobigroup/gmtsar#26]
**Describe the bug**
Merging appears to "trip up" when generating what I assume are temporary files (corr.PRM, ALL_F123.PRM). I have attempted to limit the number of jobs to 6 at a time (20 threads available on my machine) in the hopes that that may help but it has not.

**To Reproduce**
Steps to reproduce the behaviour: I am generating a large time-series of all swath sentinel-1. For now, all of the year 2015 for a particular stack (identified via ASF search stack), however I hope to expand this to multiple years in the future. I've been following your recent example of Türkiye and can't see any obvious mistakes that I've made - please let me know otherwise though!

**Screenshots**
I'll attach a few text files with log, files in processing directory and code. 

**System and software version:**
 - OS: Linux Mint 21.1 Cinnamon (pygmtsar docker)
 - GMTSAR version: 

**Processing Log**
If applicable, attach a log file from terminal output
[log.txt](https://github.com/mobigroup/gmtsar/files/11003703/log.txt)
[proce
[scriptExample.txt](https://github.com/mobigroup/gmtsar/files/11003777/scriptExample.txt)
ssing_list.txt](https://github.com/mobigroup/gmtsar/files/11003705/processing_list.txt)

[Please note that if no new responses are made over six months from users, the issue will get closed. If the report involves a simple fix in the code, the change could be done quickly; if it involves developing new features, do expect them to be done over the long run. Under both cases, the report will remain open until the issue is addressed one way or another.]

**Comment by mobigroup** [comment]
Please use maximum 2 jobs for the merging. Its well known issue of GMTSAR tools based on GMT library. I hope to rewrite this tool on pure Python in the future to resolve the problem but for now the only solution is the limited number of simultaneous merging processes (2 should be ok, otherwise use 1).

**Comment by SteffanDavies** [comment]
@mobigroup Please check my parallel merging script for GMTSAR. I've had no issues so far.

https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/merge_batch_parallel.sh

**Comment by mobigroup** [comment]
@SteffanDavies your code still calls merge_swath GMT-linked binary tool inside merge_unwrap_geocode_tops.csh For me all the GMT linked tools have the same issue on a parallel high load. Are you sure you don’t have the issue merging lots (200+) large rasters (like to 2 stitched scenes 15m resolution) using >2 parallels threads?

**Comment by mobigroup** [comment]
@SteffanDavies See #458

**Comment by SteffanDavies** [comment]
> @SteffanDavies your code still calls merge_swath GMT-linked binary tool inside merge_unwrap_geocode_tops.csh For me all the GMT linked tools have the same issue on a parallel high load. Are you sure you don’t have the issue merging lots (200+) large rasters (like to 2 stitched scenes 15m resolution) using >2 parallels threads?

I limit merge processes to available CPUs so usually 16/32 at once. Are you suggesting 200+ in parallel?

**Comment by mobigroup** [comment]
@SteffanDavies 8 processes for 200+ interferograms. The issue raises between 50 and 100 processed interferograms usually.

**Comment by SteffanDavies** [comment]
> @SteffanDavies 8 processes for 200+ interferograms. The issue raises between 50 and 100 processed interferograms usually.

My experience is on 8x raid SSD maybe that's the bottleneck you are experiencing

**Comment by mobigroup** [comment]
Yes, maybe. 8 parallel processes to read and write 6GB rasters (interferogram + correlation) each can overload iMac SSD in case of not optimal code.

**Comment by SteffanDavies** [comment]
> Yes, maybe. 8 parallel processes to read and write 6GB rasters (interferogram + correlation) each can overload iMac SSD in case of not optimal code.

I recommend testing on the cloud

**Comment by mobigroup** [comment]
I test it using different environments from 4GB RAM Docker containers and Google Colab instances and up to powerful cloud hosts. There is no reason why it shouldn’t work everywhere.

**Comment by mobigroup** [comment]
@benwright151 The recommended n_jobs=1, see https://github.com/mobigroup/YamchiDam/blob/main/notebooks/Yamchi_Dam_1_intf-large.ipynb and https://hub.docker.com/r/mobigroup/pygmtsar
```
# use n_jobs=1 in case of "FileNotFoundError" error, for details see https://github.com/gmtsar/gmtsar/issues/458
sbas.merge_parallel(pairs, n_jobs=1)
```

**Comment by benwright151** [comment]
I feel the combination of the Yamchi Dam and this ticket cover this issue.
