### ISSUE TITLE
[Help]: HTTPError: 401 Client Error: Unauthorised for URL

### ISSUE THREAD

**Issue by benwright151** [mobigroup/gmtsar#29]
**Describe the problem you met**
Hi again, thank you for your help so far! Data processing worked fine yesterday however, this morning there seems to be an issue when attempting to download orbit files. Have you encountered this problem? Usually I'd wait to see if asf itself was down, but there doesn't seem to be any notification on their end as of yet, and the style of error had me concerned that it may be something more extreme.

**OS and software version**
OS: Linux Mint (21.1 Cinnamon) , pygmtsar docker (mobigroup/pygmtsar, 6cd0e53e4011)

**Reproduce the problem**
I've attempted to run my own script and one of your jupyter notebooks - same issue both times. 

**Log
[log.txt](https://github.com/mobigroup/gmtsar/files/11147707/log.txt)
 file**

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particularly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
Usually that means the default orbits serving backend doesn’t respond and the alternative backend requires the credentials, see for details: https://github.com/scottstanie/sentineleof/issues/31
So just try to repeat the downloading some hours later or tomorrow and it should work again.
