### ISSUE TITLE
[Bug]:  Unwrapping error - FileNotFoundError: [Errno 2] No such file or directory: 'raw_asc/F123_20180105_20180210_unwrap.out'

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#31]
32 Thread / 128 GB RAM

Snaphu conf:

![image](https://user-images.githubusercontent.com/50405969/230749739-8539fb79-aac2-47e4-9eed-584801ab4341.png)

unwrap_parallel():

![image](https://user-images.githubusercontent.com/50405969/230749758-4a4324f2-33b3-40a5-8edd-8110861c0f17.png)

**Comment by mobigroup** [comment]
Unwrapping is incomplete, try to unwrap a single interferogram in debug mode and check the output (where the wrong parameters should be noted).

**Comment by mobigroup** [comment]
As I remember, I’ve explained the situation in a GMTSAR ticket: SNAPHU tiling unwrapping can be unsuccessful and in batch processing we do not know when and why. The solution is to check SNAPHU debug output for a single interferogram and tune the parameters as suggested while it does not work.
