### ISSUE TITLE
[Help]: Fail to export netcdf file even with dask modifications

### ISSUE THREAD

**Issue by benwright151** [mobigroup/gmtsar#33]
**Describe the problem you met**
I've been reading your Yamchi Dam notebooks and adapting my own script accordingly. I have now added in the SBAS.pickle file and certain checks to avoid unnecessary reprocessing. However, when running on a large enough dataset, dask seems to fail due to a memory error. I've attempted to process a netCDF with all dates, and when that didn't work I attempted to iterate through the dates individually with a simple for-in loop which gets me further - but still fails before completion. Problems start at line 8386 in the log.txt supplied below. I have increased the chunk size and I am using tqdm_dask/ cluster with n_workers at 1 and dask.persist, instead of dask.compute as from what I'm reading that works better for large datasets. I've also increased the timeouts to 60 seconds. I'm attempting to process 94 Sentinel-1 SLC IW images (with all three sub swaths of data merged). 

Keeping an eye on my memory, I do not see it exceeding anything beyond reasonable (~60%), specs:
- 12th Gen Intel© Core™ i7-12700H × 14 (20 threads)
- 32GB RAM

**OS and software version**
OS: Linux Mint (Cinnamon 21.1) with mobigroup/pygtmsar docker (id: 6cd0e53e4011)

**Log file**
[log.txt](https://github.com/mobigroup/gmtsar/files/11213814/log.txt)
[script.txt](https://github.com/mobigroup/gmtsar/files/11213815/script.txt)

**Comment by mobigroup** [comment]
You have mixed lat/lon and y/x coordinates, resulting in an enormous grid of 2580 x 3340 x 3268 x 4252, which does not fit within a reasonable amount of RAM:
```
<xarray.DataArray (lat: 2580, lon: 3340, y: 3268, x: 4252)>
dask.array<getitem, shape=(2580, 3340, 3268, 4252), dtype=float32, chunksize=(512, 512, 1024, 1024), chunktype=numpy.ndarray>
...
```

**Comment by benwright151** [comment]
Thank you for spotting my silly mistake.
