### ISSUE TITLE
[Feature]: OpenStreetMap roads mask

### ISSUE THREAD

**Issue by mobigroup** [mobigroup/gmtsar#34]
@SteffanDavies

See this new example notebook on Google Colab:
https://colab.research.google.com/drive/1xhVedrIvNS66jGKgS30Dgqy0S31uJ8gm?usp=sharing

![image](https://user-images.githubusercontent.com/7342379/231811689-ac157bee-54cb-4742-830b-44c67193bddd.png)

**Comment by SteffanDavies** [comment]
@mobigroup osmnx seems to have compatibility issues with pygmtsar / dask, I will explain in detail by email.

**Comment by mobigroup** [comment]
Please test with the recent PyGMTSAR library on PyPI, which addresses compatibility issues with modern numpy and pandas libraries. By the way, starting from Pandas 2.0, the library uses the PyArrow backend instead of numpy. This update ensures that the PyGMTSAR library remains compatible and efficient with the latest libraries and their features. Make sure to use the updated PyGMTSAR library for seamless integration and improved performance.

**Comment by mobigroup** [comment]
@SteffanDavies OSM processing works now in a separate process and it does not interfere with the main code. Also, the unwrapping is much more accurate for the masked OSM roads. In case you still see some unwrapping issues try SNAPHU config option INITMETHOD='MCF':
```
config = sbas.PRM().snaphu_config(...,INITMETHOD='MCF')
sbas.unwrap_parallel(..., conf=config)
``` 

![compare](https://user-images.githubusercontent.com/7342379/233342813-cf626862-8189-4fca-a0ea-f4cd055964da.jpg)

Additionally, I plan to implement a different approach for merging SNAPHU tiles in the future.
