### ISSUE TITLE
UnicodeDecode Error while running sbas.stack_parallel() 

### ISSUE THREAD

**Issue by soroushyasini** [mobigroup/gmtsar#35]
hi, i was testing Pygmtsar for the first time. I started to do SBAS Process with 6 SLC images and 12 days of temporal baseline. i went along with live tutorials and then faced with the following problem : 

***************************************************************************************
nicodeDecodeError                        Traceback (most recent call last)
/tmp/ipykernel_7140/1628302268.py in <module>
----> 1 sbas.stack_parallel()

~/anaconda3/lib/python3.9/site-packages/pygmtsar/SBAS_stack.py in stack_parallel(self, dates, n_jobs, **kwargs)
    233         # prepare secondary images
    234         with self.tqdm_joblib(tqdm(desc='Aligning', total=len(dates)*len(subswaths))) as progress_bar:
--> 235             joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(self.stack_rep)(subswath, date, **kwargs) \
    236                                            for date in dates for subswath in subswaths)

~/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

~/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

~/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/anaconda3/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    444                     raise CancelledError()
    445                 elif self._state == FINISHED:
--> 446                     return self.__get_result()
    447                 else:
    448                     raise TimeoutError()

~/anaconda3/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    389         if self._exception:
    390             try:
--> 391                 raise self._exception
    392             finally:
    393                 # Break a reference cycle with the exception in self._exception

UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 0: ordinal not in range(128)
********************************************************************************************************************************
what should I do to solve this problem ?

**Comment by mobigroup** [comment]
What is your system and default encoding? You would try the steps below:

1. Check if you have the recent PyGMTSAR installed.
2. Check if your paths include non-ascii characters (and remove them).
3. Use Python 3.10

**Comment by soroushyasini** [comment]
here is process directory : /home/soroush/proc
I also attached the sub-directories below :  
![Screenshot from 2023-04-18 20-50-23](https://user-images.githubusercontent.com/119971742/232841244-5e8a58f2-9d03-4be7-8585-53358e1d24a0.png)

the strange thing is, on sbas.stack_parallel() function, the  reference part seems to be OK ( since the .SLC , .PRM and .LED of the reference image are created successfully, but the error occurs while Alignin is running, as it can be seen on this screenshot below : 
 
![Screenshot from 2023-04-18 20-58-29](https://user-images.githubusercontent.com/119971742/232843849-8444990c-882e-4539-b387-d758673bcf5c.png)
![Screenshot from 2023-04-18 20-53-17](https://user-images.githubusercontent.com/119971742/232843885-36a875cf-cb94-4a3c-8998-c41f334c70f7.png)

and regarding to your Question, yes my system language and encoder is UFT-8 as it can be seen below : 

![Screenshot from 2023-04-18 20-52-35](https://user-images.githubusercontent.com/119971742/232844280-120e6ec9-b5a5-440a-8f0d-92d5011cc161.png)

**Comment by soroushyasini** [comment]
forget to mention that I installed pygmtsar again with anaconda 2023 and now python version is "Python 3.10.9"
