### ISSUE TITLE
[Bug]:  sbas_parallel - PicklingError: Could not pickle the task to send it to the workers.

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#36]
System: Ubuntu / 32 CPU / 128 GB RAM

When running sbas_parallel I get the following error:

```
%%time
# process the full unwrap grid (correlation grid will be cropped if needed)
sbas.sbas_parallel(pairs, mask=composite_road_mask)
```

> Computing: 10%
> 65/620 [01:17<11:23, 1.23s/it]
> ---------------------------------------------------------------------------
> _RemoteTraceback                          Traceback (most recent call last)
> _RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/queues.py", line 125, in _feed
>     obj_ = dumps(obj, reducers=reducers)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 211, in dumps
>     dump(obj, buf, reducers=reducers, protocol=protocol)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 204, in dump
>     _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
>     return Pickler.dump(self, obj)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/distributed/client.py", line 465, in __getstate__
>     return self.key, self.client.scheduler.address
> AttributeError: 'NoneType' object has no attribute 'address'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> PicklingError                             Traceback (most recent call last)
> File <timed eval>:2
> 
> File ~/.local/lib/python3.10/site-packages/pygmtsar/SBAS_sbas.py:202, in SBAS_sbas.sbas_parallel(self, pairs, mask, data, corr, chunks, chunksize, n_jobs)
>     200 # process all the chunks
>     201 with self.tqdm_joblib(tqdm(desc='Computing', total=ys*xs)) as progress_bar:
> --> 202     filenames = joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(func)(iy, ix) \
>     203                                              for iy in range(ys) for ix in range(xs))
>     205 # rebuild the datasets to user-friendly format
>     206 das = [xr.open_dataarray(f, engine=self.engine, chunks=chunksize) for f in filenames]
> 
> File ~/.local/lib/python3.10/site-packages/joblib/parallel.py:1098, in Parallel.__call__(self, iterable)
>    1095     self._iterating = False
>    1097 with self._backend.retrieval_context():
> -> 1098     self.retrieve()
>    1099 # Make sure that we get a last message telling us we are done
>    1100 elapsed_time = time.time() - self._start_time
> 
> File ~/.local/lib/python3.10/site-packages/joblib/parallel.py:975, in Parallel.retrieve(self)
>     973 try:
>     974     if getattr(self._backend, 'supports_timeout', False):
> --> 975         self._output.extend(job.get(timeout=self.timeout))
>     976     else:
>     977         self._output.extend(job.get())
> 
> File ~/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py:567, in LokyBackend.wrap_future_result(future, timeout)
>     564 """Wrapper for Future.result to implement the same behaviour as
>     565 AsyncResults.get from multiprocessing."""
>     566 try:
> --> 567     return future.result(timeout=timeout)
>     568 except CfTimeoutError as e:
>     569     raise TimeoutError from e
> 
> File /usr/lib/python3.10/concurrent/futures/_base.py:458, in Future.result(self, timeout)
>     456     raise CancelledError()
>     457 elif self._state == FINISHED:
> --> 458     return self.__get_result()
>     459 else:
>     460     raise TimeoutError()
> 
> File /usr/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
>     401 if self._exception:
>     402     try:
> --> 403         raise self._exception
>     404     finally:
>     405         # Break a reference cycle with the exception in self._exception
>     406         self = None
> 
> PicklingError: Could not pickle the task to send it to the workers.

**Comment by SteffanDavies** [comment]
Completed successfully by removing road mask, limiting dask local cluster to 1 worker and using n_jobs=4.

**Comment by mobigroup** [comment]
Is the composite_road_mask dask array or not? It should be computed first due to performance reasons but maybe it's important for the serialization too.

**Comment by SteffanDavies** [comment]
> Is the composite_road_mask dask array or not? It should be computed first due to performance reasons but maybe it's important for the serialization too.

That could be the problem. I will try this soon.

**Comment by mobigroup** [comment]
The latest release of PyGMTSAR resolves the issue with Dask array unwrapping masks (the mask is saved to disk once and read from disk by all unwrapping processes). As a result, it's now the preferred method to apply lazy (Dask array) masks. Additionally, unwrapping is more accurate when using phase nearest interpolation instead of zero-filling for masked areas (GMTSAR doesn't use this approach by default due to the slow interpolation script).
