### ISSUE TITLE
[Feature]: Range cropping based on pins

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#38]
GMTSAR (and PyGMTSAR) crop bursts based on pins. However, this only applies to azimuth axis. Cropping Range axis based on pins will limit unnecessary processing for interferograms and unwrapping for smaller AOI. I haven't seen any notebook examples where this is performed.

**Comment by SteffanDavies** [comment]
![image](https://user-images.githubusercontent.com/50405969/236369269-001516b3-0282-4673-9fab-7493a40c5f9f.png)

In this extreme example, 95% of pixels are not valid and only increase memory utilization and processing time in Snaphu. By setting pins around AOI, a much smaller area would require processing.

**Comment by SteffanDavies** [comment]
From my experience with GMTSAR, a minimum number of bursts (2+?) is usually required to properly process data. Cropping to a single burst seems to cause issues (related to orbital vector calculations perhaps).

**Comment by mobigroup** [comment]
I don't remember the specific example, but you can use a cropped mask for unwrapping to limit the spatial extent of the processing area. Additionally, the interferogram post-processing function can further crop interferogram and correlation grids, in addition to the usual decimation. By the way, currently, masked areas are filled using nearest interpolation, so the processing should be much faster (and more accurate) than before when these areas were filled with zeros.

> From my experience with GMTSAR, a minimum number of bursts (2+?) is usually required to properly process data. Cropping to a single burst seems to cause issues (related to orbital vector calculations perhaps).

I didn't encounter this issue during my tests, but perhaps it depends on the source scenes. If you find any problems, please share the examples so I can check them.

**Comment by SteffanDavies** [comment]
> I don't remember the specific example, but you can use a cropped mask for unwrapping to limit the spatial extent of the processing area. Additionally, the interferogram post-processing function can further crop interferogram and correlation grids, in addition to the usual decimation. 

I will try this, thanks. Also I noticed the function parameters in intf and unwrap are called post-processing, but it seems more like pre-processing to me, because it is applied to input data before the operation. Am I wrong or is the name incorrect?

>By the way, currently, masked areas are filled using nearest interpolation, so the processing should be much faster (and more accurate) than before when these areas were filled with zeros.

Hmm, if this is the case (default behaviour) why does your example use "interpolator" function with nearest grid as input pre-processing function for sbas.unwrap()? Using this function makes this particular unwrap take longer, not faster. I am slightly confused.

> > From my experience with GMTSAR, a minimum number of bursts (2+?) is usually required to properly process data. Cropping to a single burst seems to cause issues (related to orbital vector calculations perhaps).
> 
> I didn't encounter this issue during my tests, but perhaps it depends on the source scenes. If you find any problems, please share the examples so I can check them.

Maybe this has been corrected I'm not sure.

https://github.com/gmtsar/gmtsar/issues/22#issuecomment-631587073

**Comment by mobigroup** [comment]
> Maybe this has been corrected I'm not sure. https://github.com/gmtsar/gmtsar/issues/22#issuecomment-631587073

Okay. I asked for the changes to process 7+ stitched scenes, and it should fix all the issues when we don't have enough orbit records.

**Comment by mobigroup** [comment]
There is the internal interpolation BEFORE we call SNAPHU:

```
        # prepare SNAPHU input files
        # NaN values are not allowed for SNAPHU phase input file
        # interpolate when exist valid values around and fill zero pixels far away from valid ones
        self.nearest_grid(phase.where(binmask)).fillna(0).astype(np.float32).values.tofile(phase_in)
        # NaN values are not allowed for SNAPHU correlation input file
        # just fill NaNs by zeroes because the main trick is phase filling
        corr.where(binmask).fillna(0).astype(np.float32).values.tofile(corr_in)

        # launch SNAPHU binary (NaNs are not allowed for input but returned in output)
        argv = ['snaphu', phase_in, str(phase.shape[1]), '-c', corr_in,
                '-f', '/dev/stdin', '-o', unwrap_out, '-d']
        if conncomp:
            argv.append('-g')
            argv.append(conncomp_out)
        if debug:
            argv.append('-v')
            print ('DEBUG: argv', argv)
        p = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             encoding='ascii', bufsize=10*1000*1000)
```

This code interpolates large enough areas around valid pixels to simplify the solution search for SNAPHU. Pixels far away from valid ones are filled with zeroes because it's faster, and they cannot influence the solution for valid pixels. GMTSAR provides a similar script, snaphu_interp.csh, but it cannot be used in many cases because the nearest_grid tool is extremely slow.

**Comment by SteffanDavies** [comment]
> > Hmm, if this is the case (default behaviour) why does your example use "interpolator" function with nearest grid ...
> 
> This is the post-processing function applied to the output unwrapped grid after all the processing.

I see thank you for clarification. I should probably remove it then.

**Comment by mobigroup** [comment]
The nearest interpolation before SNAPHU unwrapping is one of the recent changes. I tested it for a long time to ensure that it works better than zero-filling. Also, in GMTSAR publications, this is the recommended way to prevent sudden phase changes to zero. And when we have fast lazy interpolation even for huge grids, there is no reason to use zero-filling.

**Comment by SteffanDavies** [comment]
Cropping mask NaNs changes unwrap result, it seems very wrong to me:

Original "ideal" result (no cropping, single tile unwrapping)
![image](https://user-images.githubusercontent.com/50405969/236482005-ff165faf-b755-4384-861a-8f7ea9f3c0fa.png)

Cropped
![image](https://user-images.githubusercontent.com/50405969/236480940-8d93d0b1-4377-4179-9d0c-887a4660ef20.png)

Cropped - vmin vmax

![image](https://user-images.githubusercontent.com/50405969/236481644-0982a130-d9c3-43c9-bfc3-b9109a895a7e.png)

**Comment by SteffanDavies** [comment]
In the last case, binary composite mask was cropped using sel() function:

![image](https://user-images.githubusercontent.com/50405969/236483519-d84e236b-5970-43b7-bd0d-169d37191199.png)

**Comment by mobigroup** [comment]
Do you have a different unwrapping result when cropping the mask to use single-tile unwrapping? In my tests, we have a much better solution with nearest interpolation around valid pixels, and even with a small buffer, the result is correct, as seen in issue #34. If it does not work for you, then a larger buffer around the road might be required, I think.

![](https://user-images.githubusercontent.com/50405969/236369269-001516b3-0282-4673-9fab-7493a40c5f9f.png)

**Comment by SteffanDavies** [comment]
Yes the result is different, let us compare:

- Single tile with normal mask (Time = 30s)
![image](https://user-images.githubusercontent.com/50405969/236485020-b30cb18e-6c0e-4450-a2c1-7d61c2381d07.png)

- Single tile with cropped mask (Time = 15m00s)
![image](https://user-images.githubusercontent.com/50405969/236485395-1d6893d9-c88d-428e-8a57-b1b625e4a36c.png)

**Comment by mobigroup** [comment]
Please ensure that you are using the latest PyGMTSAR library from PyPI. Additionally, it's better to compare detrended results, at a minimum by subtracting the average value.

**Comment by SteffanDavies** [comment]
Less agressive NaN slicing of composite mask now provides "correct" results (most similar to original composite road + coherence + land mask).

"Bad" slice:

"Good" slice:

**Comment by mobigroup** [comment]
"Good" slice above looks more aggressive because includes less valid pixels on the mask…

**Comment by SteffanDavies** [comment]
Was using 2023.04.20, updated to 2023.05.03, 2pi jumps are the same. 

![image](https://user-images.githubusercontent.com/50405969/236495707-d9d97767-e4fe-4ebc-ab8a-fedbeb72c705.png)

**Comment by SteffanDavies** [comment]
Latest version of PyGMTSAR is broken on my setup. Pandas error makes it impossible to unwrap.
