### ISSUE TITLE
[Bug]: PyGMTSAR (2023.5.3) - cannot unwrap, pandas error

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#39]
![image](https://user-images.githubusercontent.com/50405969/236504350-281820a0-5271-4f69-9451-cdb1d5b67e3f.png)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File ~/.local/lib/python3.10/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File ~/.local/lib/python3.10/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
File <timed exec>:11

File ~/.local/lib/python3.10/site-packages/pandas/core/frame.py:3807, in DataFrame.__getitem__(self, key)
   3805 if self.columns.nlevels > 1:
   3806     return self._getitem_multilevel(key)
-> 3807 indexer = self.columns.get_loc(key)
   3808 if is_integer(indexer):
   3809     indexer = [indexer]

File ~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 0

**Comment by SteffanDavies** [comment]
![image](https://user-images.githubusercontent.com/50405969/236507144-8b648162-fb3c-45ae-93cb-930f15b99594.png)

**Comment by mobigroup** [comment]
Yes, please pay attention that the pairs are now a pandas DataFrame instead of a NumPy array to simplify the manipulations and include additional columns like "duration". This is a silent change for most users because parallel functions work as before. I’ve shared a set of notebooks to illustrate new features, see https://www.patreon.com/posts/pygmtsar-python-82433177
