### ISSUE TITLE
[Help]: topo_ra_parallel() problem with all cores

### ISSUE THREAD

**Issue by simonst7** [mobigroup/gmtsar#4]
Hello @mobigroup , I am getting an error when I try to use all the processing cores in my workstation  to generate the  topo in radar coordinates with topo_ra_parallel()
![image](https://user-images.githubusercontent.com/53209067/193433073-4e58dab9-a674-486d-8635-87d5123c91bf.png)

when I limit the amount of cores, that is fixed and the topo_ra file with the trans data file are created 
![image](https://user-images.githubusercontent.com/53209067/193433080-4834eec2-2879-437e-90bf-0136cb7096f9.png)

Do you have any idea what that problem might be? I remember that in previous versions of pygmtsar that worked well. 

Thank you in advance

**Comment by mobigroup** [comment]
Yes, I see the problem. As the topography processing was updated we have the parallel computing for DEM chunks and the error fired when one of the processed chunks is empty. Could you share your notebook or the scenes plus subswaths to make the fix?

**Comment by mobigroup** [comment]
Ok, I think I've reproduced it. The issue fixed in PyGMTSAR package version 2022.10.2. Please confirm does it work for you?

**Comment by simonst7** [comment]
hi @mobigroup , now it is fixed, working now.
![image](https://user-images.githubusercontent.com/53209067/193470478-80484556-317d-4a9b-a7ee-1c9a4e406449.png)
thank you!

**Comment by mobigroup** [comment]
@simonst7 Great, thanks for the notification!
