### ISSUE TITLE
[Bug]: We have uploaded 2 SAR snapshots, during unwrapping it runs indefinitely

### ISSUE THREAD

**Issue by sbaqdaulet** [mobigroup/gmtsar#42]
Hello! Could you help us? We have uploaded 2 SAR snapshots, during unwrapping it runs indefinitely
![Изображение WhatsApp 2023-05-10 в 18 09 49](https://github.com/mobigroup/gmtsar/assets/133119007/1a5b7a31-6c70-4621-b2c5-282230b3be88)

**Comment by mobigroup** [comment]
Try to use sbas.unwrap(…, debug=True) for a single pair unwrapping with debug information. In addition to error messages, sometimes SNAPHU unwrapping tool prints suggestions how to tune its parameters to complete the processing.
