### ISSUE TITLE
[Help]: Issues writing high resolution los results to netcdf

### ISSUE THREAD

**Issue by benwright151** [mobigroup/gmtsar#44]
**Describe the problem you met**
Thank you for all your help so far. I seem to be having a similar problem to last time with regards to not being able to output a netcdf file from the los displacement measurements. However, this time I believe the issue has been caused by my attempt to increase the resolution of the data from 90 metres to 30 metres. This is causing a significant increase in RAM usage, so much so that the dask worker restarts several times before finally failing. I see with your Yamhi Dam 4th notebook that you export the last date from the xarray. As I need all results between first and last I attempted to iterate through the dates with a simple "for in" loop. However, even with this - I get a similar problem with the worker failing consistently at about 90% when writing a single date. Would you be able to point me in the right direction to resolve this issue? I've made sure to check the shape properly this time and everything looks appropriate (72 dates with lat and long). I've included the script underneath the logs, the log itself is relatively small as I am using your sbas.pickle approach to avoid unnecessary processing. lines 220 to 240 which are currently commented out are my proposed method for iteration through the array.

Same as before I am using your suggestions from your Yamchi Dam example, i.e:
- chunk size: 1024
- n_worker: 1
- Dask increase of timeouts to 60s
- Dask Persist/ tqdm_dask for the NetCDF export

Resources:
- 12th Gen Intel© Core™ i7-12700H × 14 (20 threads)
- 32GB RAM

**OS and software version**
OS: Linux Mint (Cinnamon 21.1) with mobigroup/pygtmsar docker (id: a25ad61c3c30)

**Log file**
[inSAR-30m_res_log_test.txt](https://github.com/mobigroup/gmtsar/files/11517725/inSAR-30m_res_log_test.txt)
[script.txt](https://github.com/mobigroup/gmtsar/files/11517786/script.txt)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
This is a lazy 3D cube created by your code:
```
sbas_disps = sbas.open_grids(dates, 'disp', func=[sbas.los_displacement_mm])
sbas_disps_total_ll = sbas.intf_ra2ll(sbas_disps.cumsum('date'))
```
And you saved it into NetCDF but it cannot be saved to GeoTIFF because it is 3D dataset:
```
delayed = sbas_disps_total_ll.to_netcdf(filename_nc, engine=sbas.engine, compute=False)
tqdm_dask(dask.persist(delayed), desc='Saving Total Displacement as NetCDF')
```
That's more effective to rearrange the commands and use loop adding the current raster to total sum instead of cumsum('date') call (it is a computationally expensive operation) when you just need a set of 2D rasters:
```
disp = sbas.open_grids(dates, 'disp', func=[sbas.los_displacement_mm])

# convert coordinate to valid dates
disp['date'] = pd.to_datetime(disp.date)

# save NetCDF files into separate directory
dirname = f'{WORKDIR}.displacement'
!mkdir -p {dirname}
!rm -f {dirname}/displacement*.nc

# for faster processing add new grid to materialized sum of the previous ones
# do not use .cumsum() function on lazy stack to process all the grids
disp_total = None
for (idx, disp_current) in enumerate(disp):
    date = disp_current.date.dt.strftime('%Y%m%d').item()
    if disp_total is None:
        disp_total = disp_current.compute()
    else:
        disp_total += disp_current.compute()
    #print (idx,date)
    filename = f'{dirname}/displacement.{date}.nc'
    sbas.intf_ra2ll(disp_total).to_netcdf(filename, engine=sbas.engine)
    print ('.', end='')
```

We can optimize the code, add "sbas.intf_ra2ll" call directly to the sbas.open_grids call (disp_ll = sbas.open_grids(dates, 'disp', func=[sbas.los_displacement_mm, sbas.intf_ra2ll])) and so on. Actually, it does not related to PyGMTSAR itself but to a big data processing on Python and I share the examples on my Patreon: https://www.patreon.com/pechnikov

By the way, what is the reason to produce GeoTIF files when NetCDF files can be opened in almost any GIS software like to GDAL, QGIS, etc.?

**Comment by benwright151** [comment]
Thank you for your detailed suggestion, that definitely produces a result where none existed before. However, I'm a little concerned that the different methods to output the netcdf/ geotiff are causing an offset to occur somehow. I'd carried out an export using the lazy grid methodology on a smaller batch of data and got the following result:
![before_shapefile](https://github.com/mobigroup/gmtsar/assets/104324816/d6d52cbd-e42e-4f5b-bacb-6b9c8131fa99)

However, when using the new methodology, I get a completely different output:
![after_shapefile](https://github.com/mobigroup/gmtsar/assets/104324816/a7f2a43f-0178-4568-b7fa-268e4cd5ad85)

I thought that it may be the coherence stack mask somehow causing less data to be available with a longer time series, however on closer inspection it looks as if the data has "shifted" northwards. See example below:
![before_](https://github.com/mobigroup/gmtsar/assets/104324816/0168fbc4-b16f-4d3c-834b-12c61e001829)

![after](https://github.com/mobigroup/gmtsar/assets/104324816/6d575c84-0145-499a-8acd-6d29601b9b91)

![both](https://github.com/mobigroup/gmtsar/assets/104324816/4f964a8c-cd86-46fa-bb0a-6f9a1d7dd1fa)

As you can see there's an exceedingly similar-looking displacement output at slightly different locations. To answer your other question as to why I am attempting to convert the netCDF to geoTIF within the code instead of after the fact - I believe there was a bug in the version of xarray outside of the docker environment and I had problems utilizing gdal or other geospatial packages to resolve the problem at the time. The conversion of a 3D data stack to GeoTIF seemed to be working perfectly with lower resolution imagery and seems to still work when utilizing a high res 2D array. Is there any particular reason why I should not be doing it this way? Do you have any potential suggestions as to why I am experiencing a shift? Many thanks in advance!

**Comment by mobigroup** [comment]
You might try the example notebook https://colab.research.google.com/drive/1xhVedrIvNS66jGKgS30Dgqy0S31uJ8gm?usp=sharing

and export disp_total.nc. As it uses the OSM mask, the results should fit well with the OSM map in QGIS:

<img width="1130" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/da39e3cd-ea1a-46e7-a5ca-6a040c6d0981">

**Comment by benwright151** [comment]
I had a look at the example notebooks you mentioned above and couldn't see any differences with the way you're geocoding so attempted to replicate my theory on the exact same small (3 full slc images) batch of data. Both output methodologies produced the exact same data grid which fits nicely with the OpenStreetMap layer available on QGIS.

What I am therefore confused about is how changing the total number of dates processed and the master image of the inSAR dataset can cause a geographic shift in my output result. To save on space I removed 6 months of data so would have ended up with a different master image (as at the moment I am not specifically setting one). 

Is this something you have experienced before or do you think it may well be a mistake on my part? I know that the critical baseline is an important concept to understand in inSAR theory, but I didn't believe that this could lead to an actual shift in a resulting displacement raster?

Many thanks in advance for your response!

**Comment by mobigroup** [comment]
Maybe do you use the same geocode matrix for the different master images? For the complete processing I cannot imagine how the shift is possible.

**Comment by benwright151** [comment]
No, everything is calculated independently for each stack of imagery. I'll run some further tests this week and let you know if I can replicate the problem.
