### ISSUE TITLE
memory leak error while executing 'SBAS LOS Displacement in Geographic Coordinates'

### ISSUE THREAD

**Issue by soroushyasini** [mobigroup/gmtsar#48]
hi, as it can be seen on the screenshot below, I faced full memory and than a killed proccess while running 'SBAS LOS Displacement in Geographic Coordinates, [mm]' static plot.
i changed Dask worker and thread configurations in sever different manner but the result was the same. 
I implemented 8 SLC data and only 1 subswath which created 11 interfrogerams.
I used a Ubuntu 20.04 machine a core i7 9th with 8 cores with 64 Gig Ram and also 25 Gig of swap space. the program was run alongside of Anaconda 2023.10.3 
If i must provide any further information, please let me know.
![Screenshot from 2023-06-13 19-05-52](https://github.com/mobigroup/gmtsar/assets/119971742/7cc99277-48ec-45a0-8026-580a9ae23518)

**Comment by mobigroup** [comment]
That's hard to understand the issue because this small analysis requires just 8-16 GB RAM. You'd start from the examples to check your configuration: https://hub.docker.com/r/mobigroup/pygmtsar-large or https://github.com/mobigroup/YamchiDam/tree/main/notebooks
