### ISSUE TITLE
[Bug]: Correction Needed in SBAS_dem.py 

### ISSUE THREAD

**Issue by gjustin40** [mobigroup/gmtsar#50]
Hello,
I have noticed an error in a section of your code and would like to suggest a correction in [SBAS_dem.py](https://github.com/mobigroup/gmtsar/blob/ebaf7a577b5ffbd0201bc0861a43d5fe7158f2db/pygmtsar/pygmtsar/SBAS_dem.py#L184)

```python
if product == 'SRTM1':
    resolution = '03s'
```
to
```python
if product == 'SRTM1':
    resolution = '01s'
```

Thanks.

**Comment by mobigroup** [comment]
Thanks, it’s already fixed in my development branch where the DEM processing is completely rewritten.
