### ISSUE TITLE
[Help]: Understanding each process of InSAR

### ISSUE THREAD

**Issue by gjustin40** [mobigroup/gmtsar#52]
Thank you for providing Python-based code about InSAR. 
I am a beginner who has just started studying SAR/InSAR, and I would like to understand the principles behind each process (D-InSAR, SBAS) while looking at the code. 
Did you refer to any specific resources while writing the code? I assume you based it on GMTSAR, but were there any additional references you used to understand the theory?

Or do you have any recommended resources?

Thanks

**Comment by mobigroup** [comment]
Hi, I had been developing the theoretical basics and lab equipment for interferometry and holography in photopolymers in university so satellite interferometry

**Comment by gjustin40** [comment]
I was actually considering that book very positively. 
However, I was concerned that the content might be more focused on the developmental aspect. But now that you mentioned that it delves deep into the theoretical explanations as well, I will study through the book!

By the way, are the posts on Patreon written in such a way that the workflow of D-InSAR corresponds directly to the theory and code for each process?

**Comment by mobigroup** [comment]
The posts cover just some points but not all the PyGMTSAR features. By the way, you need open access posts only. And my book preview is publicly available on Patreon too (and the full book for sponsors). The InSAR related topics explained in the GMTSAR book https://topex.ucsd.edu/gmtsar/tar/GMTSAR_2ND_TEX.pdf while PyGMTSAR includes much more features (PS and SBAS analysis, trends analysis and so on).

**Comment by gjustin40** [comment]
Looking at the material you mentioned (GMTSAR_2ND TEX), it seems that the processes for each stage of the code written in PyGMTSAR and the variable names in the code match up!
Thank you.

**Comment by mobigroup** [comment]
Please pay attention that PS, SBAS and trend decomposition are time series analysing methods and these are not related to interferometry processing.

**Comment by gjustin40** [comment]
Thank you for your advice. @mobigroup 

Just to clarify, does the phrase "not related to interferometry processing" mean that in the overall process of time series analysis, interferometry is simply a step to generate interferograms, and the actual time-series analysis takes place after the formation of interferograms? 
Therefore, the focus should be on the post-interferometry processes rather than interferometry itself.
Right?

**Comment by mobigroup** [comment]
Persistent scatterers detection works on image amplitudes before interferogram creation and SBAS works on unwrapped interferogram phases (not the interferogram directly).
