### ISSUE TITLE
[Help]: Error with the SBAS combine PS workflow

### ISSUE THREAD

**Issue by gaiyf** [mobigroup/gmtsar#59]
**Hello everyone when i run the workflow SBAS in Pycharm, the error occurred:**

![Screenshot from 2023-08-17 13-20-51](https://github.com/mobigroup/gmtsar/assets/57431511/b0ed107d-496b-4447-8f5f-bb7f37d97b5e)

**I have already set the PATH parm:**

![Screenshot from 2023-08-17 13-21-36](https://github.com/mobigroup/gmtsar/assets/57431511/c9ed64c3-243d-4bd7-aa5d-e9547f76a030)

**when i run the command in cmd with python, another problem occurred:**

![Screenshot from 2023-08-17 13-29-00](https://github.com/mobigroup/gmtsar/assets/57431511/a926432a-26b6-4e3c-9d21-701107f0b909)

**Comment by mobigroup** [comment]
See #37

**Comment by gaiyf** [comment]
Thanks, it works!!! 
but the **_sbas.ps_parallel()_**  problem seems troublesome.
![Screenshot from 2023-08-17 17-35-56](https://github.com/mobigroup/gmtsar/assets/57431511/4b55e926-3d2d-4303-90a1-7e69f0d8002f)

**Comment by mobigroup** [comment]
To use the ps_parallel() function you need to install the exact PyGMTSAR commit from github as it performed in the notebook.
