### ISSUE TITLE
[Help]: Installation

### ISSUE THREAD

**Issue by laxmangeo** [mobigroup/gmtsar#60]
Hi sir
         I used GMTSAR for mapping city subsidence in wsl, I want to work in  pygmtsar, how I install pygmtsar in wsl, is there any manual like GMTSAR installation?

**Comment by mobigroup** [comment]
You can use PyGMTSAR on Google Colab in cloud environment and in Docker containers locally and in clouds without installation. See the introduction book for details. Also, in case you already have GMTSAR installed on your host you just need to install PyGMTSAR Python library.

**Comment by laxmangeo** [comment]
thank you sir
