### ISSUE TITLE
[Help]: Adding onto existing displacement results

### ISSUE THREAD

**Issue by benwright151** [mobigroup/gmtsar#61]
**Describe the problem you met**
I'm looking to make an updating displacement "service" that searches for new Sentinel-1 files and adds them on to an existing time series. For example, I have already processed a displacement time series for 2021-2022 for a particular stack and I want to add Jan 2023 Sentinel-1 scenes for the same area. The key point is that I don't want to regenerate 2021-2022 interferograms to save time if at all possible. I want to continue the processing by only processing new interferogram baseline pairs (using the basedays and basemeters features). 

My initial idea is to utilise the pandas features of your SBAS object and at a certain point append the new data to the existing dataframe, then filter using the datetime and carry that through to the point just before running sbas_parallel (i.e interferogram generation/ unwrapping etc) and then re-adding the full time-series df. However, when calling an sbas.df and appending to it, it loses the SBAS object type. 

Another idea would be to create a new data folder containing all the relevant data (new data - 100 days), generate interferograms/ unwarp and then physically move the data into the existing time series working directory and use SBAS.restore (I am already dumping all data after interferogram generation anyway). However, I'm not sure how SBAS.restore/ the pickle file would handle that?

Could you let me know if any of this makes sense to you, if so - whether it's a good idea or not/ whether it is possible?

Would it be better to reprocess the entire DATADIR with the new Sentinel-1 scenes?

Thanks in advance!

**Comment by AlexeyPechnikov** [comment]
@benwright151 We're able to regenerate all SBAS pairs or a selected subset by combining recently processed dates with new ones, and filter out existing pairs. However, it's important to note that all pairs need to be reprocessed for least-squares and seasonal trend decomposition, as these algorithms require the full timeseries. While generating interferograms is typically a quick process, SNAPHU unwrapping can be time-consuming. Despite this, significant time savings are possible in some cases.
