### ISSUE TITLE
[Help]: Extract tiff data from SLC zip file that I need for analysis.

### ISSUE THREAD

**Issue by gjustin40** [mobigroup/gmtsar#62]
Hi!
Is there a way to automatically extract only the Swath and burst data I need from an SLC data zip file? 
As far as I know, I have to manually unzip the zip file and select the required tiff files, which can be a time-consuming process. 

Is there a better way to do this?
Thanks

**Comment by AlexeyPechnikov** [comment]
The unpacking code is already included into the Google Colab examples, see this and other notebooks: https://colab.research.google.com/drive/12LJqlZNBUmvLlRl98rRFCbKveVPg9Ami?usp=sharing

```
SCENES = ['S1A_IW_SLC__1SDV_20171111T150004_20171111T150032_019219_0208AF_EE89',
          'S1B_IW_SLC__1SDV_20171117T145900_20171117T145928_008323_00EBAB_B716',
          'S1B_IW_SLC__1SDV_20171117T145926_20171117T145953_008323_00EBAB_AFB8']
SUBSWATH     = 3
POLARIZATION = 'VV'
...
    for scene in SCENES:
        ...
        for subswath in str(SUBSWATH):
            !unzip -j -n {scene}.zip '*.SAFE/*/s1?-iw{subswath}-slc-{POLARIZATION.lower()}-*' -d {DATADIR}
```

**Comment by gjustin40** [comment]
Thanks!

Do you have any plans to encapsulate this task as a function in Python?

**Comment by AlexeyPechnikov** [comment]
This shell code is quite straightforward. In the future, I'm considering reading GeoTIFF files directly from the archive without unpacking them at all.

**Comment by gjustin40** [comment]
That sounds great! 
Thank you for always providing valuable content and code. 
I'll make good use of PyGMTSAR!
