### ISSUE TITLE
[Help]: East/West and Vertical displacement explanation

### ISSUE THREAD

**Issue by benwright-davra** [mobigroup/gmtsar#65]
**Describe the problem you met**
Hi, I've been looking into East/West and Vertical displacement and from the reading from SNAP and other forums, as well as scientific literature - I am led to believe that you can only calculate East/West and Vertical displacement if you have both ascending and descending orbits. 

However, in your PyGMTSAR_Türkiye_Earthquakes_2023_01_29_2023_02_10_2scenes example, you have a section whereby you calculate east/west and vertical, yet you only seem to be using descending orbits. Could you please explain how you've gone about it? 

Thanks so much in advance!

**Comment by AlexeyPechnikov** [comment]
Displacement vector projection components in vertical and horizontal directions can be calculated using a single orbit. However, this is equal to the actual vertical and horizontal displacements only when all other components are zero. This means that when you know the real displacement is mostly vertical or horizontal, you can use the single-orbit estimation. However, when you need to calculate both components accurately, simply compute an average value for the components between the two orbits.
