### ISSUE TITLE
[Help]: The Open Access orbits server is currently unavailable

### ISSUE THREAD

**Issue by laxmangeo** [mobigroup/gmtsar#68]
dear Author,
                  i got error when i am downloading orbit files
![orbit_files](https://github.com/mobigroup/gmtsar/assets/127308214/ba3a9205-6ac2-47c8-bd60-b836e968b1bb)

**Comment by AlexeyPechnikov** [comment]
The open access orbits server is currently unavailable, which affects password-less orbits downloading. To address this issue, I've updated the example notebooks with a workaround, as described below. In the development version of PyGMTSAR, you can use the ASF module to quickly download Sentinel-1 scenes and orbits from the Alaska Satellite Facility (ASF) datastore, although user registration is required.

```
# Workaround: Public access to orbits is currently unavailable.
username = 'sifts0_spangle@icloud.com'
password = 'cnjwdchuwe&e9d0We9'
!echo "machine dataspace.copernicus.eu login {username} password {password}" > ~/.netrc
!chmod 600 ~/.netrc
# also, you can place pre-downloaded orbit files in the data directory
sbas.download_orbits()
```

**Comment by laxmangeo** [comment]
Thank you sir , and one more thing I used 32 scenes ,I got space  issuses, is there any solution rather than purchase.

**Comment by AlexeyPechnikov** [comment]
Do you need to process only specific subswaths or a limited area? Processing all three subswaths for 32 scenes would require over 120GB of disk space, which can be challenging even on a paid Google Colab account.

**Comment by laxmangeo** [comment]
Yes sir, even not only fully subswath(a small city)

**Comment by laxmangeo** [comment]
yes sir with in subswath only ( a small city)

**Comment by AlexeyPechnikov** [comment]
In this case, please refer to this notebook for the development PyGMTSAR version, which focuses on a small area intersecting two subswaths: https://colab.research.google.com/drive/1d9RcqBmWIKQDEwJYo8Dh6M4tMjJtvseC?usp=sharing We still need to store the source Sentinel-1 SLC GeoTIFF files, which amounts to 32 scenes * 1.5GB, totaling 48GB for a single subswath. This dataset can be further cropped to include only the required bursts, reducing it to approximately 5GB for a single-burst, single-subswath dataset across 32 scenes. Additionally, you can crop it further to match your area of interest to minimize the processing data size and used disk space.

![](https://user-images.githubusercontent.com/7342379/280638338-3fa8b309-6238-411a-8bf3-e6e33f81fe86.png)

![](https://user-images.githubusercontent.com/7342379/280638361-c5fc1584-f205-4eec-b88d-87cd1b300e0c.png)

**Comment by laxmangeo** [comment]
Thank you sir, i will do
