### ISSUE TITLE
[Help]: Fail in downloading Sentinel-1 orbits

### ISSUE THREAD

**Issue by firaterdem** [mobigroup/gmtsar#69]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
I am trying to run a notebook titled "ASF Downloading 2020 Ardabil, Iran Earthquake Co-Seismic Interferogram and LOS Displacement" in Google Colab. However, I am getting an error in downloading the Sentinel-1 orbits part.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: I am using Google Colab. OS information is given as follows.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?
The problem is appearing in the following line of the code:

sbas.download_orbits()

**Log file**
Attach a log file output from your terminal.

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-27-0786330a1dda>](https://localhost:8080/#) in <cell line: 2>()
      1 # also, we can place pre-downloaded orbit files to data directory
----> 2 sbas.download_orbits()

6 frames
[/usr/lib/python3.10/netrc.py](https://localhost:8080/#) in __init__(self, file)
     28         self.macros = {}
     29         try:
---> 30             with open(file, encoding="utf-8") as fp:
     31                 self._parse(file, fp, default_netrc)
     32         except UnicodeDecodeError:

FileNotFoundError: [Errno 2] No such file or directory: '/root/.netrc'

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![SS](https://github.com/mobigroup/gmtsar/assets/19222333/45b8b56c-fba3-455b-a61a-7dbfb533e917)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
The open access orbits server is currently unavailable, which affects password-less orbits downloading. To address this issue, I've updated the example notebooks with a workaround, as described below. In the development version of PyGMTSAR, you can use the ASF module to quickly download Sentinel-1 scenes and orbits from the Alaska Satellite Facility (ASF) datastore, although user registration is required.

```
# Workaround: Public access to orbits is currently unavailable.
username = 'sifts0_spangle@icloud.com'
password = 'cnjwdchuwe&e9d0We9'
!echo "machine dataspace.copernicus.eu login {username} password {password}" > ~/.netrc
!chmod 600 ~/.netrc
# also, you can place pre-downloaded orbit files in the data directory
sbas.download_orbits()
```

**Comment by firaterdem** [comment]
I passed that part with your new script. Thank you so much.
