### ISSUE TITLE
[Help]: error: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Jonk98** [mobigroup/gmtsar#7]
Hello @mobigroup,  
I am sorry for the other question but I am getting an error when i use decimation.
I don't understand why at times using different scenes from the same area of interest the code works fine but at other times it won't, reporting the error message I've attached here.

![Screenshot (49)](https://user-images.githubusercontent.com/115569345/195893991-127e9f6f-e75d-45ff-b64f-97595892eb24.png)
![Screenshot (50)](https://user-images.githubusercontent.com/115569345/195894010-60bd4070-a68d-4502-aa27-6d62cead51d8.png)

**Comment by mobigroup** [comment]
Hi @Jonk98 This code is suitable for a single interferogram creation using 2 scenes only. Show your "pairs" variable value to check:
```
pairs
```
