### ISSUE TITLE
[Help]: Problem in downloading images

### ISSUE THREAD

**Issue by firaterdem** [mobigroup/gmtsar#70]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

I am trying to run a notebook titled "S1A_Stack_CPGF_T173_v2.ipynb" in Google Colab. However, I am getting an error in downloading the Sentinel-1 data.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: I am using Google Colab. OS information is given as follows.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

The problem is appearing in the following line of the code:

asf = ASF(username, password)
asf.download(DATADIR, SCENES, SUBSWATH, POLARIZATION)

Also, "Define Sentinel-1 SLC Scenes and Processing Parameters" part is as follows. I think there may be a problem at this part because I couldn't understand how can I set these parameters (subswath, etc.). 

SCENES = ['S1A_IW_GRDH_1SDV_20190703T155937_20190703T160002_027955_03280F_DEA4',
          'S1A_IW_GRDH_1SDV_20200709T155944_20200709T160009_033380_03DE13_1EEF',
          'S1A_IW_GRDH_1SDV_20210704T155949_20210704T160014_038630_048EEC_F2B2',
          'S1A_IW_GRDH_1SDV_20220723T155957_20220723T160022_044230_05476D_EEAB',
          'S1A_IW_SLC__1SDV_20230706T155959_20230706T160026_049305_05EDC1_AD0D']
SUBSWATH = 1
POLARIZATION = 'VV'

REFERENCE    = '2021-10-07'
WORKDIR      = 'raw_stack'
DATADIR      = 'raw_orig'
BASEDAYS     = 100
BASEMETERS   = 150

**Log file**
Attach a log file output from your terminal.

remotezip.RemoteIOError: 404 Client Error: NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_GRDH_1SDV_20200709T155944_20200709T160009_033380_03DE13_1EEF.zip
"""

The above exception was the direct cause of the following exception:

RemoteIOError                             Traceback (most recent call last)
<ipython-input-14-07b9e14324c7> in <cell line: 3>()
      1 # download required polarization and subswaths only
      2 asf = ASF(username, password)
----> 3 asf.download(DATADIR, SCENES, SUBSWATH, POLARIZATION)

6 frames
/usr/local/lib/python3.10/dist-packages/joblib/parallel.py in _return_or_raise(self)
    752         try:
    753             if self.status == TASK_ERROR:
--> 754                 raise self._result
    755             return self._result
    756         finally:

RemoteIOError: 404 Client Error: NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_GRDH_1SDV_20200709T155944_20200709T160009_033380_03DE13_1EEF.zip

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

![SS_1](https://github.com/mobigroup/gmtsar/assets/19222333/b266ea06-61bd-4176-9fd5-b3ca6820a516)
![SS_2](https://github.com/mobigroup/gmtsar/assets/19222333/3d49ae49-b1f5-4393-a75c-b35641563f9d)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
You replaced the original SLC scenes by GRD products. You need to select SLC scenes for InSAR processing.

**Comment by firaterdem** [comment]
> You replaced the original SLC scenes by GRD products. You need to select SLC scenes for InSAR processing.

Yes, I replaced them with SLC sences and problem solved. However, I am getting another error at the SBAS Baseline line as follows. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-27-cd271f1f8166> in <cell line: 1>()
----> 1 baseline_pairs = sbas.baseline_pairs(days=BASEDAYS, meters=BASEMETERS)
      2 baseline_pairs

3 frames
/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py in _get_label_or_level_values(self, key, axis)
   1842             values = self.axes[axis].get_level_values(key)._values
   1843         else:
-> 1844             raise KeyError(key)
   1845 
   1846         # Check for duplicates

KeyError: 'ref_date'



I am not sure about how can I select the following parameters (BASEDAYS and BASEMETERS).

SCENES = ['S1A_IW_SLC__1SDV_20190703T155936_20190703T160002_027955_03280F_7A00',
          'S1A_IW_SLC__1SDV_20200709T155942_20200709T160009_033380_03DE13_6BE3',
          'S1B_IW_SLC__1SDV_20210710T155906_20210710T155932_027734_034F4D_3658',
          'S1A_IW_SLC__1SDV_20220723T155955_20220723T160022_044230_05476D_C9E5',
          'S1A_IW_SLC__1SDV_20230718T160000_20230718T160027_049480_05F324_473C']
SUBSWATH = 1
POLARIZATION = 'VV'

REFERENCE    = '2021-07-10'
WORKDIR      = 'raw_stack'
DATADIR      = 'raw_orig'
BASEDAYS     = 100
BASEMETERS   = 150

**Comment by firaterdem** [comment]
Using SLC scenes has solved the problem. Thank you.
