### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by laxmangeo** [mobigroup/gmtsar#71]
Respected sir,
                    I follow your example https://colab.research.google.com/drive/1h4XxJZwFfm7EC8NUzl34cCkOVUG2uJr4?usp=sharing#scrollTo=bU_MlX1X_XQG for local city subsidence(~80 cm). my results were not good, here I attached correlation, unwrapped interferograms, detrend interferograms and cumulative displacement. Please help me 
![cummu_disp](https://github.com/mobigroup/gmtsar/assets/127308214/fdf5a596-3399-415f-98ea-6d574e07b821)
![detrend](https://github.com/mobigroup/gmtsar/assets/127308214/1c930642-7ffb-4d60-ba76-5c2c0b5cd17e)
![unwrapped](https://github.com/mobigroup/gmtsar/assets/127308214/a6147f67-ff66-431c-92e3-47b50a03f2ed)
![correlation](https://github.com/mobigroup/gmtsar/assets/127308214/dd77fbbb-1e4c-4d9a-a035-9e6ae7b2ce5a)

**Comment by AlexeyPechnikov** [comment]
Your results are too noisy and we cannot see the subsidence on the displacement map while it is visible on the detrended unwrapped phase. Filter your interferograms or remove atmospheric noise. More accurately selected Gaussian detrending parameters can help a lot. Also, I share more complicated examples on Patreon for subscribers.

**Comment by laxmangeo** [comment]
Hi Sir, 
               I tried several ways to change the Gaussian filtering cut-off wavelength with multi-looking and detrend Gaussian wavelengths, but I couldn't find subsidence in the displacement map. And to do atmospheric correction in pygmtsar.
Please give me the solution.

**Comment by AlexeyPechnikov** [comment]
![284818864-a6147f67-ff66-431c-92e3-47b50a03f2ed](https://github.com/mobigroup/gmtsar/assets/7342379/aa11a4b8-547b-4af9-bad7-16fe0005df2b)

Do you mean this area?

**Comment by laxmangeo** [comment]
![coh](https://github.com/mobigroup/gmtsar/assets/127308214/337749fc-8508-4eaa-91b3-b9b94ed25f1c)
![py](https://github.com/mobigroup/gmtsar/assets/127308214/7cdfd384-9c5f-4850-ba3e-bb02c593f7ba)
This area sir, has almost 50 cm subsidence is there

**Comment by AlexeyPechnikov** [comment]
I asked you about the exact location of the subsidence, as I've marked on your plots.

**Comment by laxmangeo** [comment]
No sir, that is not the location, I marked the exact location on the above images with red color circles

**Comment by laxmangeo** [comment]
![py](https://github.com/mobigroup/gmtsar/assets/127308214/81549d80-0c32-4ec3-9ec3-6098f6b71b1c)

**Comment by AlexeyPechnikov** [comment]
Ok, and how look your detrended results?

**Comment by laxmangeo** [comment]
![detrend_pygmtsar](https://github.com/mobigroup/gmtsar/assets/127308214/dd38d50b-6eb6-4a83-9610-48e4564c81a6)
Sir, this are detrended interferograms

**Comment by AlexeyPechnikov** [comment]
It appears that you are not using the Goldstein filter. A Gaussian filter with a 400m radius and multilooking of 1:4 (or 2:8), along with a Goldstein filter having a patch size of 32 (or 16), should work for you.

**Comment by laxmangeo** [comment]
No sir, Already i was used that parameters.

**Comment by laxmangeo** [comment]
![LOS](https://github.com/mobigroup/gmtsar/assets/127308214/ef3112be-09f6-4e55-9a95-b730c5a419a0)
 LOS with that parameters

**Comment by AlexeyPechnikov** [comment]
In this scenario, I suggest plotting the AOI in radar coordinates to ensure you are examining the correct location. Alternatively, it's possible that the AOI is too small and the entire area is subsiding uniformly. For a subsidence rate of 80cm/year, we would expect to observe significant synchronous changes in all interferograms, but that's not apparent here.
