### ISSUE TITLE
[Bug]: it si not executing in Docker 

### ISSUE THREAD

**Issue by dotsLand** [mobigroup/gmtsar#72]
**Describe the bug**
in Colab it work well, but in docker is not working well in PS, SBAS work OK 
this is notebooks that i try to execute in Docker 
https://github.com/mobigroup/gmtsar/blob/pygmtsar2/notebooks/GasteinValley_v2.ipynb

**To Reproduce**
I used a last docker and updated a library last pygimstar2 and also dask

**Screenshots**
![image](https://github.com/mobigroup/gmtsar/assets/107835719/8e06e4bf-7475-4d50-9342-425693eac150)

**System and software version:**
 - GMTSAR version:

**Processing Log**
If applicable, attach a log file from terminal output

[Please note that if no new responses are made over six months from users, the issue will get closed. If the report involves a simple fix in the code, the change could be done quickly; if it involves developing new features, do expect them to be done over the long run. Under both cases, the report will remain open until the issue is addressed one way or another.]

**Comment by AlexeyPechnikov** [comment]
It looks as outdated numba library incompatibility. You need to upgrade all the python libraries because the Docker image is built a long time ago for previous PyGMTSAR version.

**Comment by dotsLand** [comment]
an after updates same :
![image](https://github.com/mobigroup/gmtsar/assets/107835719/905869f1-7ab8-420c-99ce-a641ffa0f952)

**Comment by AlexeyPechnikov** [comment]
What is the version of your Numba library? Check it using the following command:
```
import numba
print(numba.__version__)
```

**Comment by dotsLand** [comment]
it is 
numba 0.56.4

**Comment by AlexeyPechnikov** [comment]
It is outdated; I have Numba 0.58.1. Your version is not compatible with the recent Python and NumPy libraries because support was added in version [0.57.0](https://github.com/numba/numba/releases/tag/0.57.0): 'A new release of Numba adding support for Python 3.11, NumPy 1.24.'

**Comment by dotsLand** [comment]
I rebuild all image for docker and work well, thank you
