### ISSUE TITLE
[Help]: Results are not seem accurate

### ISSUE THREAD

**Issue by firaterdem** [mobigroup/gmtsar#73]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

I am trying to run a notebook titled "S1A_Stack_CPGF_T173_v2.ipynb" in Google Colab. However, the results seem not accurate. dX and dY values are very close to each other. This causes the displacement vectors to always appear diagonal. I'm adding a screenshot of this.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: I am using Google Colab. OS information is given as follows.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

You access the complete code in the following link:

https://drive.google.com/file/d/1Gsq7fjIyqaU4GktMCZYzbCxoGZU6NV95/view?usp=sharing

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

Following SS is the visualization of the velocities at the random points:

![Diplacements](https://github.com/mobigroup/gmtsar/assets/19222333/935e30cd-51dd-425f-8771-c8d5378eeacb)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
It seems you are trying to export a lazy grid and produce a square output grid. You need to check your output grid dimensions.

**Comment by firaterdem** [comment]
> id. You need to check your output grid dimensions.

Thank you very much for your response. But, I couldn't understand how can I correct this. In the shared Colab code, which line should I change and how can I do it?

**Comment by AlexeyPechnikov** [comment]
That's hard to understand in your shared notebook on Google Drive:
<img width="1920" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/716a04dd-a5a7-43e5-8ad7-5845a04b4398">

Typically, you can call `compute()` before saving to NetCDF to prevent the issue.
