### ISSUE TITLE
[Help]: Error downloading EOF files

### ISSUE THREAD

**Issue by shivamthescienceguy** [mobigroup/gmtsar#74]
hie alexey,
when i installed python3 -m pip install sentineleof for downloading eof files

after eof command i got this error and couldn't download orbit files
[error_orbit.txt](https://github.com/mobigroup/gmtsar/files/13668626/error_orbit.txt)

could you please tell me why

**Comment by AlexeyPechnikov** [comment]
The text file is empty. By the way, the latest version of PyGMTSAR now includes its own downloader for Sentinel-1 scenes and orbits.

**Comment by SteffanDavies** [comment]
Hi, is this related to 401 authorisation error? I am also having problems with downloading orbits and too many sessions.
