### ISSUE TITLE
[Help]: Stack function error related to "orbitpath column"

### ISSUE THREAD

**Issue by teagamrs** [mobigroup/gmtsar#75]
Hi, i'm trying to run the GasteinValley_v2.ipynb in jupyter notebook in an Anaconda environment running in a Ubuntu 20.04.6 LTS OS and pygmtsar-v2023.3.11.
After the images download, i have the directory with images and orbits but this error occurs and i'm not capable to find where is the "orbitpath".

**Log file**
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 sbas = Stack(WORKDIR, drop_if_exists=True).set_scenes(scenes).set_reference(REFERENCE)
      2 sbas.to_dataframe()

File ~/anaconda3/envs/interferometry/lib/python3.11/site-packages/pygmtsar/Stack.py:59, in Stack.set_scenes(self, scenes)
     57 def set_scenes(self, scenes):
     58     assert len(scenes), 'ERROR: the scenes list is empty.'
---> 59     assert len(scenes[scenes.orbitpath.isna()])==0, 'ERROR: orbits missed, check "orbitpath" column.'
     60     self.df = scenes
     61     if self.reference is None:

AssertionError: ERROR: orbits missed, check "orbitpath" column.
```

The adapted code is attached. This is my first issue and i'm trying to cover all the context but If there's any info missing please ask. Thank you very much.
[InterferometryProcessing.zip](https://github.com/mobigroup/gmtsar/files/13704964/InterferometryProcessing.zip)
![Screenshot from 2023-12-18 11-18-36](https://github.com/mobigroup/gmtsar/assets/150672080/a936c7da-a3fd-4995-8cdb-1786144de6ff)

**Comment by AlexeyPechnikov** [comment]
This notebook requires the library installed from GitHub (see Google Colab installation section in the notebook) where the development library version is available. PiPy library version provides SBAS processing only.

**Comment by teagamrs** [comment]
> #Installing pygmtsar
> !git clone https://github.com/mobigroup/gmtsar.git /home/thamires/anaconda3/envs/interferometry/lib/python3.11/site-packages/gmtsar
> !pip install /home/thamires/anaconda3/envs/interferometry/lib/python3.11/site-packages/gmtsar/pygmtsar

Hi, thank you for response. This part above is in my code. I believe that I download correctly from Git, dont I?

**Comment by AlexeyPechnikov** [comment]
pip can install the library right from GitHub without cloning the repo. Just specify the correct branch and directory as in the Google Colab notebooks.

**Comment by teagamrs** [comment]
I'll try!

**Comment by teagamrs** [comment]
Hi, I've tried again: The environment was deleted and a new one created. To install pygmtsar,  instead the code in my previous post, I used this one from the session Install Python Modules in notebook:

```
#Installing pygmtsar
!pip install git+https://github.com/mobigroup/gmtsar.git@pygmtsar2#subdirectory=pygmtsar 
```
Now the version is Version: 2023.11.18a0 but unfortunately the same error appeared. 
![Screenshot from 2023-12-18 15-54-13](https://github.com/mobigroup/gmtsar/assets/150672080/a6ccace0-a19f-4478-82de-505b3f61fd1a)

**Comment by AlexeyPechnikov** [comment]
Here is the error: “ERROR: orbits missed, check “orbitpath” column.” The column is not visible on your screenshot.

**Comment by teagamrs** [comment]
The orbitpath column is there. But, I adjusted the width column settings to take a capture for this discussion and this showed to me that 2 scenes didnt have orbits. So I unlisted them from scenes def and now is working. Thank you Alexey!
