### ISSUE TITLE
[Help]: Not covering all AOI after REFRAME

### ISSUE THREAD

**Issue by dotsLand** [mobigroup/gmtsar#76]
**Describe the problem you met**
Not covering all burst from two subswath in AOI:

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
here are scenes and AOI in WKT
SCENES = """
S1A_IW_SLC__1SDV_20210216T165012_20210216T165039_036618_044D49_3209
S1B_IW_SLC__1SDV_20210210T164932_20210210T164959_025547_030B4D_CB0B
S1A_IW_SLC__1SDV_20210204T165013_20210204T165040_036443_044729_EF31
S1A_IW_SLC__1SDV_20210123T165013_20210123T165040_036268_04411C_C038
S1B_IW_SLC__1SDV_20210117T164932_20210117T164959_025197_030006_0F2C
S1A_IW_SLC__1SDV_20210111T165014_20210111T165041_036093_043B07_5BAA
S1A_IW_SLC__1SDV_20201230T165014_20201230T165041_035918_0434F0_0C67
S1B_IW_SLC__1SDV_20201224T164933_20201224T165000_024847_02F4D0_7638
S1A_IW_SLC__1SDV_20201218T165015_20201218T165042_035743_042EC4_9553
S1B_IW_SLC__1SDV_20201212T164934_20201212T165001_024672_02EF22_E214
S1A_IW_SLC__1SDV_20201206T165015_20201206T165042_035568_0428C4_947B
S1B_IW_SLC__1SDV_20201130T164935_20201130T165002_024497_02E97C_D85E
S1A_IW_SLC__1SDV_20201124T165016_20201124T165043_035393_0422BD_67C6
S1B_IW_SLC__1SDV_20201118T164935_20201118T165002_024322_02E3F1_BAF9
"""
SCENES = list(filter(None, SCENES.split('\n')))
print (f'Scenes defined: {len(SCENES)}')

ORBIT     = 'A'
SUBSWATH  = 23
REFERENCE = '2020-11-18'

wkt = 'POLYGON((16.2271 45.6098,15.9904 45.5241,15.9177 45.2826,16.3538 45.2282,16.5381 45.326,16.5369 45.4997,16.2271 45.6098))'

**Log file**
Attach a log file output from your terminal.

**Screenshot**
Before reframing
![image](https://github.com/mobigroup/gmtsar/assets/107835719/e2baed87-4126-47e0-83d8-f5b83c992c26)

After reframe
![image](https://github.com/mobigroup/gmtsar/assets/107835719/32ee0de3-deee-46d5-be68-0cb07490b7c2)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
The plots depict approximate locations calculated using Sentinel-1 reference ground points for a burst defined at zero height. To ensure that your processing patch encompasses the Area of Interest (AOI), it's recommended to add a buffer (defined in decimal degrees) around it. For instance, a 0.05-degree buffer equates to approximately 5 km:

```
AOI = gpd.GeoDataFrame.from_features([json.loads(geojson)])
AOI['geometry'] = AOI.buffer(0.05)
AOI
```

**Comment by dotsLand** [comment]
Actually I am  using a buffer 0.02 but I will try also with 0.05

**Comment by AlexeyPechnikov** [comment]
Actually, this can be sufficient since the plots are approximate. You could opt to continue processing to verify, or simply add a larger buffer to ensure it encompasses the AOI.

**Comment by dotsLand** [comment]
thnx  but it takes a lot of time on processing over 14h specially on sync_cube(unwrap_snaphu.....
can you try it in your environment with those of scenes and AOI sample notebooks GasteinValley_weighted_v2.ipynb

https://github.com/mobigroup/gmtsar/blob/pygmtsar2/notebooks/GasteinValley_weighted_v2.ipynb

**Comment by AlexeyPechnikov** [comment]
To check AOI coverage you need to align and map only two scenes without actual interferogram processing.

**Comment by dotsLand** [comment]
> To check AOI coverage you need to align and map only two scenes without actual interferogram processing.

i will try also only with two scene, this was multi0look phase from all 28 scenes:
![image](https://github.com/mobigroup/gmtsar/assets/107835719/9b5fa2a8-b722-40ce-a881-ee2cb513d10a)

**Comment by AlexeyPechnikov** [comment]
Ok, I can see some clearly visible fringes here.

**Comment by dotsLand** [comment]
even with two scenes, the processing is getting stuck at unwrap_sbas = sbas.sync_cube(unwrap_sbas, 'unwrap_sbas')
