### ISSUE TITLE
[Help]: Velocity pixel float cannot be converted from NaN to integer

### ISSUE THREAD

**Issue by teagamrs** [mobigroup/gmtsar#77]
Hi again,

i'm running the GasteinValley_v2.ipynb in jupyterlab in an Anaconda environment. I've adapted the code with my AOI and images and everything went just fine till now. I'm at the velocity section just above PS Analysis section but this error appeared: 

**Log file**
```
ValueError                                Traceback (most recent call last)
Cell In[54], line 6
      4 disp_pixel = disp_sbas.sel(y=y, x=x, method='nearest')
      5 stl_pixel = stl_sbas.sel(y=y, x=x, method='nearest')
----> 6 velocity_pixel = int(velocity_sbas.sel(y=y, x=x, method='nearest').round())
      7 plt.plot(disp_pixel.date, disp_pixel, c='r', lw=2, label='Displacement POI')
      8 plt.plot(stl_pixel.date, stl_pixel.trend, c='r', ls='--', lw=2, label='Trend POI')

File ~/anaconda3/envs/interferometry/lib/python3.11/site-packages/xarray/core/common.py:160, in AbstractArray.__int__(self)
    159 def __int__(self: Any) -> int:
--> 160     return int(self.values)

ValueError: cannot convert float NaN to integer

```

**OS and software version**
Ubuntu 22.04.3 LTS OS and pygmtsar 2023.11.18a0

The adapted code is attached. Anyone can help me please? If there's any info missing please ask. Thank you very much.
[InterferometryProcessing.zip](https://github.com/mobigroup/gmtsar/files/13788200/InterferometryProcessing.zip)

**Comment by AlexeyPechnikov** [comment]
It means the selected pixel displacements are not defined (NaN) and the convertion to integer value is not possible. Select other pixel which is processed.

**Comment by teagamrs** [comment]
Hi, when in code this selection occurs?

**Comment by teagamrs** [comment]
Oh I think I get it. It's my POI and POI0. I'll try with others points. Thank you!
