### ISSUE TITLE
[Feature]: Protecting against missing frames

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#78]
A very confusing situation can happen when there is a missing frame in a stack of scenes. For example, when combining S1A and S1B for an AOI:

- S1A  has 1 frame covering AOI
- S1B has 2 frames covering AOI

I have witnessed a scenario where for some reason, there is a day where S1B is missing its contiguous frame. Processing will continue normally until we perform SBAS cumulative displacement and find that half the data is missing. 

To prevent this, it would be advisable to check if the users AOI is totally included in every single concatenated frame geometry for each date, and exclude the problematic date at the start of the processing.

This has happened in PyGMTSAR stable but I haven't tested this problem in PyGMTSAR 2.

**Comment by AlexeyPechnikov** [comment]
In the new PyGMTSAR version, handling missed interferograms (NaN phase values) shouldn't be a problem, as the least-squares solution for displacement computation is now capable of managing these cases. I think it's better to allow scenes that do not completely cover the AOI, as achieving full coverage (for all scenes) is sometimes unattainable.
