### ISSUE TITLE
[Feature]: Please update docker image

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#79]
Latest PyGMTSAR docker image is pulling an older version of stable PyGMTSAR, and version 2023.5 is not available.  

Also is a PyGMTSAR2 docker image to be expected in the near future?

**Comment by AlexeyPechnikov** [comment]
You can upgrade the installed PyGMTSAR version in the Docker image.

A new PyGMTSAR Docker image is anticipated soon, as it already effectively combines SBAS and PSI analyses. This integration was a key objective in the development of the new version. It enables amplitude, SBAS, and PSI processing within a single notebook or script, eliminating the need for third-party software.

**Comment by SteffanDavies** [comment]
> You can upgrade the installed PyGMTSAR version in the Docker image.

I have been using this workaround for now, thanks

**Comment by AlexeyPechnikov** [comment]
For now, you can build it yourself using the repositories’s Dockerfile.

**Comment by AlexeyPechnikov** [comment]
The new Docker image is available on DockerHub: https://hub.docker.com/r/mobigroup/pygmtsar
