### ISSUE TITLE
[Bug]: sbas.merge_parallel() grouping subswaths as 32 instead of 23 causing error

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#8]
Running sbas.merge_parallel() funcion causes wrong subswath pairing (32 instead of 23) leading to error in finding files.

This is probably because the SBAS object is not correctly ordering products by subswath:

![image](https://user-images.githubusercontent.com/50405969/196932403-84e30503-bf55-496b-b0ce-5614e1d400e5.png)

Based on current grouping code, the result is this:

![image](https://user-images.githubusercontent.com/50405969/196932568-656ef17c-dc67-47c7-b84b-1cca70dfc990.png)

**Comment by SteffanDavies** [comment]
This can be solved temporarily by correctly ordering the sbas dataframe before merging:

sbas.to_dataframe().sort_values(by=["date","subswath"],inplace=True)

**Comment by mobigroup** [comment]
It looks strange because the subswaths are sorted by 'datetime' internally so it means you found the case when the subswaths timestamps are listed in reversed order. Thanks, I'll fix it of course.

**Comment by mobigroup** [comment]
@SteffanDavies The issue is fixed in pygmtsar 2022.11.12.2 and Docker image 2022-11-12, see
https://pypi.org/project/pygmtsar/
https://hub.docker.com/r/mobigroup/pygmtsar

**Comment by SteffanDavies** [comment]
Good news!

**Comment by mobigroup** [comment]
@SteffanDavies The notebooks to process 2 stitched scenes (6 full subswaths in total) using 15m resolution on Apple Air 16GB RAM available here: https://github.com/mobigroup/YamchiDam/tree/main/notebooks
