### ISSUE TITLE
[Help]: When performing the sbas.plot_scenes (AOI) operation, there is a deviation between the SLC image and the image selected by ASF

### ISSUE THREAD

**Issue by Aragon-Yggdrasil** [mobigroup/gmtsar#82]
**Describe the problem you met**
When performing the sbas.plot_scenes (AOI) operation, there is a deviation between the SLC image and the image selected by ASF

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Colab
GMTSAR version:

**Reproduce the problem**
“GasteinValley_weighted_v2_200days_80%“，Follow your steps, when previewing the image before Reframe Scenes (Optional), the size of the SLC image is different from the preview in ASF

**Log file**
        [ 109.8794, 25.8309 ]；
        [ 110.0766, 24.7612 ]；
        [ 110.947, 25.0326  ]；
        [ 111.1918, 25.8248 ]；
        [ 111.0354, 26.0816 ]；
        [ 109.8794, 25.8309 ]；
Here is my selected range
**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![下载](https://github.com/mobigroup/gmtsar/assets/151033036/e1e81315-b7ce-45e7-94f5-46fdf11ef669)
![image](https://github.com/mobigroup/gmtsar/assets/151033036/964f111a-1e9f-43d1-83a8-b1efd7a69ee1)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
Sentinel-1 scene includes 3 subswaths, but you selected the only one. It seems you need all the 3 to cover your area.

**Comment by Aragon-Yggdrasil** [comment]
> Sentinel-1 scene includes 3 subswaths, but you selected the only one. It seems you need all the 3 to cover your area.
Thank you very much for your help. After adjustment, the research area can now be included

**Comment by Aragon-Yggdrasil** [comment]
> Sentinel-1 scene includes 3 subswaths, but you selected the only one. It seems you need all the 3 to cover your area.

Thank you very much for your help. After adjustment, the research area can now be included
