### ISSUE TITLE
[Help]: During the Refrem Senes operation, the strip was cropped incorrectly

### ISSUE THREAD

**Issue by Aragon-Yggdrasil** [mobigroup/gmtsar#83]
**Describe the problem you met**
sbas.compute_reframe(AOI)，An error occurred while cropping the image

**OS and software version**
If applicable, what operating system and software version you are using?
OS: colab
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
BUFFER = 0.05

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![下载 (1)](https://github.com/mobigroup/gmtsar/assets/151033036/a84c52b4-7e8e-4e5f-8fa2-923a23bcef2e)
![下载](https://github.com/mobigroup/gmtsar/assets/151033036/ae803744-09e8-4112-8248-314db97353bf)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by AlexeyPechnikov** [comment]
Please share your AOI file and the used scenes list.

**Comment by Aragon-Yggdrasil** [comment]
This is my AOI range
   
        [ 109.446, 25.6771  ],
        [ 109.624, 24.8848 ],
        [ 110.8204, 24.7592 ],
        [ 111.1063, 25.7768 ],
        [ 110.8573, 26.092  ],
        [ 109.8426, 25.8682 ],
        [ 109.446, 25.6771  ]
This is my scenes list.
S1A_IW_SLC__1SDV_20231223T104313_20231223T104340_051781_064118_9D62
S1A_IW_SLC__1SDV_20231223T104248_20231223T104315_051781_064118_F0B7
S1A_IW_SLC__1SDV_20231211T104314_20231211T104341_051606_063B0E_65D0
S1A_IW_SLC__1SDV_20231211T104249_20231211T104316_051606_063B0E_C57B
S1A_IW_SLC__1SDV_20231129T104314_20231129T104341_051431_0634F7_63FC
S1A_IW_SLC__1SDV_20231129T104249_20231129T104316_051431_0634F7_9581
S1A_IW_SLC__1SDV_20231117T104315_20231117T104342_051256_062EED_5D38
S1A_IW_SLC__1SDV_20231117T104250_20231117T104317_051256_062EED_7730
S1A_IW_SLC__1SDV_20231105T104315_20231105T104342_051081_0628DE_4634
S1A_IW_SLC__1SDV_20231105T104250_20231105T104317_051081_0628DE_7BD5
S1A_IW_SLC__1SDV_20231024T104315_20231024T104342_050906_0622E1_EEC5
S1A_IW_SLC__1SDV_20231024T104251_20231024T104318_050906_0622E1_F00F
S1A_IW_SLC__1SDV_20231012T104315_20231012T104342_050731_061CEA_55EC
S1A_IW_SLC__1SDV_20231012T104250_20231012T104317_050731_061CEA_9B43
S1A_IW_SLC__1SDV_20230930T104316_20230930T104342_050556_0616E8_61C0
S1A_IW_SLC__1SDV_20230930T104251_20230930T104318_050556_0616E8_2D4E
S1A_IW_SLC__1SDV_20230918T104315_20230918T104342_050381_0610ED_BF21
S1A_IW_SLC__1SDV_20230918T104250_20230918T104317_050381_0610ED_12BB
S1A_IW_SLC__1SDV_20230906T104315_20230906T104342_050206_060AF8_B399
S1A_IW_SLC__1SDV_20230906T104250_20230906T104317_050206_060AF8_448C
S1A_IW_SLC__1SDV_20230825T104314_20230825T104341_050031_0604FA_1335
S1A_IW_SLC__1SDV_20230825T104249_20230825T104316_050031_0604FA_D357
S1A_IW_SLC__1SDV_20230813T104313_20230813T104340_049856_05FF08_A517
S1A_IW_SLC__1SDV_20230813T104248_20230813T104315_049856_05FF08_77C4
S1A_IW_SLC__1SDV_20230801T104313_20230801T104344_049681_05F95D_17C2
S1A_IW_SLC__1SDV_20230801T104248_20230801T104315_049681_05F95D_0B5B
S1A_IW_SLC__1SDV_20230720T104312_20230720T104344_049506_05F3F1_9F57
S1A_IW_SLC__1SDV_20230720T104247_20230720T104314_049506_05F3F1_EE80
S1A_IW_SLC__1SDV_20230708T104311_20230708T104343_049331_05EE9E_D0C4
S1A_IW_SLC__1SDV_20230708T104247_20230708T104314_049331_05EE9E_78C5
S1A_IW_SLC__1SDV_20230626T104310_20230626T104342_049156_05E936_F3D6
S1A_IW_SLC__1SDV_20230626T104245_20230626T104312_049156_05E936_1AA3
S1A_IW_SLC__1SDV_20230614T104310_20230614T104337_048981_05E3EA_FC53
S1A_IW_SLC__1SDV_20230614T104245_20230614T104312_048981_05E3EA_A5B7
S1A_IW_SLC__1SDV_20230602T104309_20230602T104336_048806_05DE8E_027D
S1A_IW_SLC__1SDV_20230602T104244_20230602T104311_048806_05DE8E_BD57
S1A_IW_SLC__1SDV_20230521T104309_20230521T104336_048631_05D95A_D4D9
S1A_IW_SLC__1SDV_20230521T104244_20230521T104311_048631_05D95A_9E27
S1A_IW_SLC__1SDV_20230509T104308_20230509T104335_048456_05D42F_23E0
S1A_IW_SLC__1SDV_20230509T104243_20230509T104310_048456_05D42F_0777
S1A_IW_SLC__1SDV_20230427T104307_20230427T104334_048281_05CE54_0414
S1A_IW_SLC__1SDV_20230427T104243_20230427T104310_048281_05CE54_4296
S1A_IW_SLC__1SDV_20230415T104307_20230415T104334_048106_05C87A_9D67
S1A_IW_SLC__1SDV_20230415T104242_20230415T104309_048106_05C87A_32B7
S1A_IW_SLC__1SDV_20230403T104307_20230403T104334_047931_05C28C_31AD
S1A_IW_SLC__1SDV_20230403T104242_20230403T104309_047931_05C28C_98C4
S1A_IW_SLC__1SDV_20230322T104306_20230322T104333_047756_05BCB0_F9B1
S1A_IW_SLC__1SDV_20230322T104241_20230322T104308_047756_05BCB0_BAF0
S1A_IW_SLC__1SDV_20230310T104306_20230310T104333_047581_05B6C0_19ED
S1A_IW_SLC__1SDV_20230310T104241_20230310T104308_047581_05B6C0_7A58
S1A_IW_SLC__1SDV_20230226T104306_20230226T104333_047406_05B0D6_52DC
S1A_IW_SLC__1SDV_20230226T104241_20230226T104308_047406_05B0D6_2672
S1A_IW_SLC__1SDV_20230214T104306_20230214T104333_047231_05AAD7_CCD0
S1A_IW_SLC__1SDV_20230214T104241_20230214T104308_047231_05AAD7_6DAE
S1A_IW_SLC__1SDV_20230121T104307_20230121T104334_046881_059F27_083A
S1A_IW_SLC__1SDV_20230121T104242_20230121T104309_046881_059F27_A838
S1A_IW_SLC__1SDV_20230109T104307_20230109T104334_046706_05993F_C0BC
S1A_IW_SLC__1SDV_20230109T104242_20230109T104309_046706_05993F_F168

**Comment by Aragon-Yggdrasil** [comment]
Is it because the selected area is too large?

**Comment by Aragon-Yggdrasil** [comment]
It's about 58 scenes, the same track

**Comment by Aragon-Yggdrasil** [comment]
I changed the width of the AOI so that when it sits on a strip, the strip can be cropped very well
![下载 (2)](https://github.com/mobigroup/gmtsar/assets/151033036/cfd194e8-a7d4-4ae7-bc6f-92c619650ef4)
![下载](https://github.com/mobigroup/gmtsar/assets/151033036/a4d24842-5ee8-41a7-87d7-18e5096048fe)

AOI

       [109.3624, 25.6768],
       [109.6699, 24.3012],
       [110.3915, 24.4266],
       [110.0693, 25.7938],
       [109.3591, 25.6697]

SCENES LIST

The list of scenes is the same as the one above

**Comment by Aragon-Yggdrasil** [comment]
But my research area occupies two strips, please Mr. Alexey do you have a solution @mobigroup

**Comment by AlexeyPechnikov** [comment]
Fixed in the recent commit, please try. 
![image](https://github.com/mobigroup/gmtsar/assets/7342379/53f0611f-d598-451d-9dc0-dfc2dbea6b4d)

**Comment by Aragon-Yggdrasil** [comment]
> Fixed in the recent commit, please try. 
> ![image](https://github.com/mobigroup/gmtsar/assets/7342379/53f0611f-d598-451d-9dc0-dfc2dbea6b4d)
> 

Thank you very much for your help, dear Mr. Alexey
