### ISSUE TITLE
[Feature]: Implementing of S1 Bursts: downloading/reframing and Aligning

### ISSUE THREAD

**Issue by dotsLand** [mobigroup/gmtsar#84]
Hello @mobigroup  

did you try to download and process S1 BURSTS from ASF Vertex?

![image](https://github.com/mobigroup/gmtsar/assets/107835719/43ac723a-051a-4cd7-8cc1-15a7739a458b)

**Comment by AlexeyPechnikov** [comment]
The bursts are not available:

<img width="1240" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/78af17ad-00a4-4acb-a8dc-9316a156f264">

<img width="1266" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/912fb138-0d19-4b45-a6ea-15661320e708">

**Comment by dotsLand** [comment]
Interesting  I have tested with AOI of  Gastein Valley POLYGON((13.1082 47.2164,13.198 47.2164,13.198 47.2545,13.1082 47.2545,13.1082 47.2164)) 

Maybe in filter is any parameters wrong:
check this :
https://search.asf.alaska.edu/#/?zoom=12.672&center=13.154,47.209&polygon=POINT(13.1041%2047.241)&resultsLoaded=true&dataset=SENTINEL-1%20BURSTS

or at your point:
https://search.asf.alaska.edu/#/?zoom=9.771&center=-91.303,-0.897&polygon=POINT(-91.45%20-0.5)&resultsLoaded=true&dataset=SENTINEL-1%20BURSTS

![image](https://github.com/mobigroup/gmtsar/assets/107835719/0398ba8d-0853-4898-ada6-105218b45680)

**Comment by AlexeyPechnikov** [comment]
Here are only bursts for the recent 6 months or about it.

**Comment by dotsLand** [comment]
yeah I see it seems there is any bug.
https://docs.asf.alaska.edu/datasets/using_ASF_data/
https://docs.asf.alaska.edu/datasets/using_ASF_data/#sentinel-1-bursts
![image](https://github.com/mobigroup/gmtsar/assets/107835719/eece6947-cfb0-4c1c-8c54-d60daac70a85)
