### ISSUE TITLE
[Bug]: plot_scenes broken for large datasets

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#85]
`gdf.reset_index().plot(color=[colors[k] for k in gdf.index], alpha=0.5/len(gdf), edgecolor='black', ax=plt.gca())`

Here, dividing alpha by len(gdf) will make the plot invisible in a long adataset.

`gdf.reset_index().plot(color=[colors[k] for k in gdf.index], alpha=0.5, edgecolor='black', ax=plt.gca())`

![image](https://github.com/mobigroup/gmtsar/assets/50405969/80c4bdcf-4084-472a-9cde-568d32e590c1)

**Comment by AlexeyPechnikov** [comment]
Yes, Matplotlib ignores geometries with an alpha value less than 0.002. We can set this threshold as a limit to prevent the issue.

**Comment by AlexeyPechnikov** [comment]
Please check 3bb4bd0
