### ISSUE TITLE
[Bug]: Inconsistent Results for Overlapping AOIs

### ISSUE THREAD

**Issue by dotsLand** [mobigroup/gmtsar#89]
I am writing to bring to your attention  that I have encountered while working with different AOIs that have an overlap area. I have performed tests using the same scenes and parameters with SBAS, yet I am receiving different results for the overlapping regions.

AOI area is 10kmx20km with buffer 0.02, overlaped area is 4km
Despite these efforts to maintain consistency, the results for the overlapping areas are diverging.

Is SBAS suitable for analyzing small surfaces, considering the significant difference observed in deformation results on a particular surface? If applicable, how can one determine which set of results from SBAS analysis should be considered more trustworthy when encountering such variations?

**Screenshots**
![2AOI](https://github.com/mobigroup/gmtsar/assets/107835719/d17495ff-935f-4889-a4d9-fe5963772bed)
Two diff AOI with OverLaps

![compare red with blue](https://github.com/mobigroup/gmtsar/assets/107835719/11e926ed-82a4-4bba-a2ce-8f573f713b35)
Results from two diff AOI

![near](https://github.com/mobigroup/gmtsar/assets/107835719/07d36c21-261d-44b9-904a-eb430f8b9ac1)
See difference in zoom, gradient of color is for  same values

 
![zoom](https://github.com/mobigroup/gmtsar/assets/107835719/c498accf-f2c2-4230-88e2-bcb045875ace)

for same point i create charts with LOS displacement and also STL,  see 

![zoom with chart](https://github.com/mobigroup/gmtsar/assets/107835719/f1c9944a-6bfc-411c-8251-55bfb488bf8d)

**System and software version:**
 - OS: Docker, latest pygmtsar
 - GMTSAR version: Latest

**Comment by AlexeyPechnikov** [comment]
SBAS results depend on unwrapping accuracy, and we need to control it effectively. This involves detrending, removing atmospheric phase, and other steps, including the removal of excessively noisy interferograms.

For example, let's compare these unwrapped interferograms where no visible patterns are apparent:

<img width="1132" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/a65de061-dded-42c7-bbe0-8b3df32f775a">

Now, take a look at the cleaned ones, where you can easily recognize a subsidence area at the center:

<img width="1128" alt="image" src="https://github.com/mobigroup/gmtsar/assets/7342379/d14f39a0-4cd1-441d-9ac6-be6662258c54">

**Comment by dotsLand** [comment]
SBAS Phase, [rad]0-100
![SBAS Phase,  rad 0-100](https://github.com/mobigroup/gmtsar/assets/107835719/6b3daa26-3985-4c17-b04b-ac2ccaa9548f)


SBAS Trend Phase, [rad]0-100
![SBAS Trend Phase,  rad 0-100](https://github.com/mobigroup/gmtsar/assets/107835719/4d684a40-b818-4268-abe5-d4d4b109f82a)


SBAS Phase - Trend, [rad]0-100.
![SBAS Phase - Trend,  rad 0-100](https://github.com/mobigroup/gmtsar/assets/107835719/962ed8e7-5b75-488f-8b6b-4d761ee5166e)



Histogram for Standard Deviation with Mean and Std Lines - pairs_best.jpg
![Histogram for Standard Deviation with Mean and Std Lines - pairs_best](https://github.com/mobigroup/gmtsar/assets/107835719/c9191298-14b9-4b9d-bf3d-0d4851999f99)

SBAS Best Pairs Quality
![SBAS Best Pairs Quality](https://github.com/mobigroup/gmtsar/assets/107835719/392d5db6-2659-4cbf-a2a3-a606ba68a90d)


SBAS Baseline - Standard Deviation
![SBAS Baseline - Standard Deviation](https://github.com/mobigroup/gmtsar/assets/107835719/7378ee43-c2ae-43cf-a9d0-2e721613fe13)


SBAS Cumulative LOS Displacement, [mm]
![SBAS Cumulative LOS Displacement,  mm](https://github.com/mobigroup/gmtsar/assets/107835719/b1f12f05-e017-477e-b309-2fbc66bd5f42)


SBAS Connected Components0100

![SBAS Connected Components0100](https://github.com/mobigroup/gmtsar/assets/107835719/4c1a86a4-9439-4af6-bfbb-cba616f7cb53)

I have tried to use a stddev < 4 but not to much change

**Comment by AlexeyPechnikov** [comment]
Your detrended phases are very noisy because you don't check the connected components map. Use unwrapping without a correlation threshold to unwrap all the pixels and prevent disconnected areas.

**Comment by dotsLand** [comment]
i will try with out correlation threshold !
