### ISSUE TITLE
AOI plot error

### ISSUE THREAD

**Issue by Smitrgeo15** [mobigroup/gmtsar#90]
How to solve this?
sbas.plot_scenes(AOI)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-22-c43939f7acfb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 sbas.plot_scenes(AOI)

[/usr/local/lib/python3.10/dist-packages/pygmtsar/Stack.py](https://localhost:8080/#) in plot_scenes(self, dem, caption, cmap, aspect, **kwargs)
    123                 dem.plot.imshow(cmap='gray', add_colorbar=False)
    124         elif dem is not None:
--> 125             dem.plot.imshow(cmap='gray', add_colorbar=False)
    126         gdf = self.to_dataframe()
    127         cmap = matplotlib.colormaps[cmap]

AttributeError: 'GeoplotAccessor' object has no attribute 'imshow'

**Comment by AlexeyPechnikov** [comment]
Use as

```
sbas.plot_scenes(AOI=AOI)
```

also, now you can add POI as points:
```
sbas.plot_scenes(AOI=AOI, POI=POI)
```

**Comment by Smitrgeo15** [comment]
thanks @mobigroup
