### ISSUE TITLE
[Help]: any way to process Envisat SAR data ?

### ISSUE THREAD

**Issue by soroushyasini** [mobigroup/gmtsar#93]
hi, i am starting to use the Docker image of PyGMTSAR, i got to assess land movement of an area in a long-term period, hence both Sentinel and Envisat must be processed. any hint to do so with pyGMTSAR? 
I also will be appreciated so much if you provide me some information on Envisat processing since i have no experience on Envisat.

**Comment by AlexeyPechnikov** [comment]
PyGMTSAR currently supports only Sentinel-1 data. I work on the project in my free time, and I don't have any grants or funding for my work, so my resources are very limited for adding support for other missions.

**Comment by soroushyasini** [comment]
alright thanks for your respond.

**Comment by AlexeyPechnikov** [comment]
See https://www.linkedin.com/feed/update/urn:li:activity:7159957590272053248/
