### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by MehdiInSAR** [mobigroup/gmtsar#95]
Hi Alexey,

I am using PyGMTSAR for the first time. I estimated the velocity map firstly using "disp_sbas" and then using "stl_sbas". The former looks normal and the later is almost zero everywhere! My velocity maps (estimated based on the stl_sbas as it is in the colab code) are always zero (green). It seems that the stl algorithm is refined or smoothed displacement values too much. Can you please guide me what could be the problem? I put my velocity maps here:
<img width="570" alt="vel_sbas_sbas-stl_2" src="https://github.com/AlexeyPechnikov/gmtsar/assets/159442038/222131d1-d173-412e-8c86-c64fba1dcea1">

Thx

**Comment by AlexeyPechnikov** [comment]
Use the `plot_baseline_displacement()` function to display the results for one stable and one unstable point. It appears that STL is applied over a one-year interval, and in this context, STL identifies the trend as constant, with an offset equal to half the slope obtained from least-squares regression. In a one-year analysis example, STL calculates B1 (slope) as 0 and B0 (offset) as 16.3, whereas the regression trend yields B1 as 36.9. Here, twice the STL B0 (16.3 x 2 = 32.6) closely approximates the regression B1 (36.9).
![](https://github.com/AlexeyPechnikov/gmtsar/assets/7342379/aa490c8e-b682-49a2-a3c8-bfcf0f8f2f77)
