### ISSUE TITLE
PS step singlelook interferogram not working

### ISSUE THREAD

**Issue by teagamrs** [mobigroup/gmtsar#97]
Hi Alexey and collegues,

i'm now following the GoldenValley notebook updated yesterday. 
This error occurs after all SBAS steps, at "compute_interferogram_singlelook" in PS section. How can I proceed with the analysis? What's going on?

- OS: Ubuntu 22.04.3 LTS
- PyGMTSAR version: '2024.1.21.post6'

**Log file**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[104], line 1
----> 1 sbas.compute_interferogram_singlelook(baseline_pairs, 'intf_slook', wavelength=400,
      2                                       weight=sbas.psfunction(), phase=trend_sbas)

AttributeError: 'Stack' object has no attribute 'compute_interferogram_singlelook'
```
**Screenshot**
![Screenshot from 2024-02-09 15-28-31](https://github.com/AlexeyPechnikov/pygmtsar/assets/150672080/fff99941-f325-48c2-97f1-76376c985e55)

**Comment by AlexeyPechnikov** [comment]
Please note that the notebook installs the most recent PyGMTSAR library from GitHub instead of PyPI. That means the required functions are not yet present in the PyPI library. You can install the GitHub library version or wait for a few days until the PyPI library is updated.

**Comment by teagamrs** [comment]
Hey, i'm using jupyter. In my adapted code, i'm using this way to install:

```
#Installing pygmtsar
!pip install git+https://github.com/mobigroup/gmtsar.git@pygmtsar2#subdirectory=pygmtsar 
from pygmtsar import __version__
__version__
```

In GoldenValley:
```
if 'google.colab' in sys.modules:
    !{sys.executable} -m pip install -Uq git+https://github.com/mobigroup/gmtsar.git@pygmtsar2#subdirectory=pygmtsar
    #!{sys.executable} -m pip install -q pygmtsar
from pygmtsar import __version__
__version__
```

The version is also returning the same. There is any difference? I don't know how to do this...

**Comment by AlexeyPechnikov** [comment]
Your command does not install a new library when a previous version is installed because you missed the '-U' pip option to do it. The correct installation command is presented in the notebook, and you cited it above.

**Comment by AlexeyPechnikov** [comment]
New PyGMTSAR (Python InSAR) Docker Images Available Now: https://www.patreon.com/posts/new-pygmtsar-now-98688871

**Comment by teagamrs** [comment]
Worked perfectly Alexey. Thank you for your explanation.

> Your command does not install a new library when a previous version is installed because you missed the '-U' pip option to do it. The correct installation command is presented in the notebook, and you cited it above.
