### ISSUE TITLE
[Bug]: POEORB and RESORB download error

### ISSUE THREAD

**Issue by antus** [mobigroup/gmtsar#99]
Hello Alexey,
during the download step of POEORB and RESORB data of your samples I 've got the following error:

ASF Downloading Sentinel-1 SLC: 100%
3/3 [00:43<00:00, 10.14s/it]
Downloading POEORB catalog:: 100%
1/1 [02:26<00:00, 146.34s/it]
ERROR: Failed to fetch the web page. Status code: {response.status_code}
Downloading RESORB catalog:: 100%
1/1 [01:00<00:00, 60.52s/it]
ERROR: Failed to fetch the web page. Status code: {response.status_code}
ERROR: some orbits not found locally and in orbit catalogs
ASF Downloading Sentinel-1 Orbits: 100%
3/3 [00:00<00:00, 23.73it/s]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py", line 261, in download_orbit
    asf_search.download_urls(urls=[url], path=basedir, session=session)
  File "/usr/local/lib/python3.10/dist-packages/asf_search/download/download.py", line 41, in download_urls
    download_url(url=url, path=path, session=session)
  File "/usr/local/lib/python3.10/dist-packages/asf_search/download/download.py", line 67, in download_url
    if os.path.isfile(os.path.join(path, filename)):
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)

**Comment by antus** [comment]
Any suggestions??

**Comment by AlexeyPechnikov** [comment]
Don’t worry, it means ASF data facility is temporary unavailable or overloaded. Just restart the notebook immediately or a bit later to download the missed orbits and continue the processing.

**Comment by oguzhannysr** [comment]
ASF Downloading Sentinel-1 SLC: 100%
19/19 [04:42<00:00, 10.51s/it]
Downloading POEORB catalog:: 100%
1/1 [00:07<00:00, 7.25s/it]
Downloading RESORB catalog:: 100%
1/1 [01:00<00:00, 60.11s/it]
ERROR: Failed to fetch the web page. Status code: {response.status_code}
ERROR: some orbits not found locally and in orbit catalogs
ASF Downloading Sentinel-1 Orbits: 100%
19/19 [00:09<00:00, 1.25it/s]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py", line 261, in download_orbit
    asf_search.download_urls(urls=[url], path=basedir, session=session)
  File "/usr/local/lib/python3.10/dist-packages/asf_search/download/download.py", line 41, in download_urls
    download_url(url=url, path=path, session=session)
  File "/usr/local/lib/python3.10/dist-packages/asf_search/download/download.py", line 67, in download_url
    if os.path.isfile(os.path.join(path, filename)):
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
[<ipython-input-18-4c11ed894de9>](https://localhost:8080/#) in <cell line: 3>()
      1 # download required polarization and subswaths only
      2 asf = ASF(username, password)
----> 3 asf.download(DATADIR, SCENES, SUBSWATH)

6 frames
[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _return_or_raise(self)
    752         try:
    753             if self.status == TASK_ERROR:
--> 754                 raise self._result
    755             return self._result
    756         finally:

TypeError: Can't mix strings and bytes in path components

**Comment by AlexeyPechnikov** [comment]
The same as above:
> Don’t worry, it means ASF data facility is temporary unavailable or overloaded. Just restart the notebook immediately or a bit later to download the missed orbits and continue the processing.

**Comment by oguzhannysr** [comment]
The problem still persists, I did what you said and it didn't work. Is it caused by ASF?

**Comment by AlexeyPechnikov** [comment]
Yes, it's the orbits downloading problem from ASF. I've already been thinking about creating my own cache for the orbits because the issue arises regularly.

**Comment by ATDehkordi** [comment]
Hi Alexey,
I have the same issue. Do you have any solutions except waiting and requesting several times?
Regards

**Comment by AlexeyPechnikov** [comment]
I've checked 10 times in the last two hours for 28-30 scenes and all the orbits have been downloaded successfully.

**Comment by ATDehkordi** [comment]
I can successfully download S1 scenes and also POEORB files.
The only problem is for RESORB files.

**Comment by ATDehkordi** [comment]
Attached is the error:
(https://github.com/AlexeyPechnikov/pygmtsar/assets/34648501/86167514-8e67-436b-8b82-0d36c24c101d)

**Comment by AlexeyPechnikov** [comment]
Yes, the catalog cannot be opened:
https://s1qc.asf.alaska.edu/aux_resorb/

```
504 Gateway Time-out
The server didn't respond in time.
```

At the same time, there is no problem with https://s1qc.asf.alaska.edu/aux_poeorb/

You can report the issue on ASF portal or just wait. I cannot resolve it because it is a server-side issue. The only way is to maintain a separate storage for all the orbits but it requires a large disk space and traffic.

**Comment by ATDehkordi** [comment]
Thanks Alexey,
But the point is that orbit data have not yet been generated for the recent S1 scenes. I could solve the problem by changing the dates of my images (getting back to about 2 months ago).
Regards

**Comment by AlexeyPechnikov** [comment]
That's possible to use this workaround for the previous PyGMTSAR version (we need to have the required library 'sentineleof' installed):
```
# Workaround: Public access to orbits is currently unavailable.
username = 'sifts0_spangle@icloud.com'
password = 'cnjwdchuwe&e9d0We9'
!echo "machine dataspace.copernicus.eu login {username} password {password}" > ~/.netrc
!chmod 600 ~/.netrc
# download from ESA datastore
!cd {DATADIR} && eof
```

**Comment by MHMoazezian** [comment]
you can  downloading RESORB files in a loop to multiple request to [https://s1qc.asf.alaska.edu/aux_resorb/](url)
`import time

max_attempts = 5  # Maximum number of attempts
attempt = 0  # Current attempt
success = False  # Flag to indicate success

asf = ASF(username, password)

while attempt < max_attempts and not success:
    try:
        attempt += 1
        print(f"Attempt {attempt} of {max_attempts}")
        asf.download(DATADIR, SCENES, SUBSWATH)
        success = True  # If download succeeds, set success to True
        print("Download successful.")
    except Exception as e:  # Catch any exception (consider specifying exact exceptions)
        print(f"An error occurred: {e}")
        time.sleep(5)  # Wait for 5 seconds before retrying (to avoid hammering the server)

if not success:
    print("Failed to download after maximum attempts.")`

**Comment by MHMoazezian** [comment]
I'm attempting to implement an automatic retry mechanism for downloading RESORB files from https://s1qc.asf.alaska.edu/aux_resorb/. 
```
import time

max_attempts = 5  # Maximum number of attempts
attempt = 0  # Current attempt
success = False  # Flag to indicate success

asf = ASF(username, password)

while attempt < max_attempts and not success:
    try:
        attempt += 1
        print(f"Attempt {attempt} of {max_attempts}")
        asf.download(DATADIR, SCENES, SUBSWATH)
        success = True  # If download succeeds, set success to True
        print("Download successful.")
    except Exception as e:  # Catch any exception (consider specifying exact exceptions)
        print(f"An error occurred: {e}")
        time.sleep(5)  # Wait for 5 seconds before retrying (to avoid hammering the server)

if not success:
    print("Failed to download after maximum attempts.")
```

**Comment by ATDehkordi** [comment]
Hey Milad,

I tried the same approach as you suggested. However, as I mentioned earlier, the problem mostly occurs with the most recently acquired scenes. For the older ones (from approximately 2-3 months ago), there is no issue with downloading the orbit data.

Thanks.

**Comment by AlexeyPechnikov** [comment]
@MHMoazezian Retries do not help when ASF RESORB are not accessible for days. See my commend above how to download the orbits from ESA datastore instead.

**Comment by AlexeyPechnikov** [comment]
Here is the solution: https://www.patreon.com/posts/pygmtsar-new-99185442
